"use client";
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {rpc} from '@/lib/supabase';
import {Fund,formatMetric,validId} from '@/lib/investments';
import {useAccount} from '@/lib/use-account';
import type {AppState,MatchItem} from '@/lib/dna';

type CompareRow=Fund&{target_allocation?:Record<string,number>;quality_score?:number};
function fitLabel(m?:MatchItem){return m?.explanation?.fit_label||m?.fit_label||m?.recommendation_tier?.replaceAll('_',' ')||'Not matched'}
export default function Compare(){
 const {user}=useAccount();const [funds,setFunds]=useState<Fund[]>([]),[selected,setSelected]=useState<string[]>(['','','']),[rows,setRows]=useState<CompareRow[]>([]),[state,setState]=useState<AppState|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;setLoading(true);const ids=new URLSearchParams(location.search).get('ids')?.split(',').filter(validId).slice(0,3)||[];if(ids.length)setSelected([ids[0]||'',ids[1]||'',ids[2]||'']);
 Promise.all([rpc<Fund[]>('app_search_investments',{p_limit:100}),user?rpc<AppState>('get_current_investor_app_state').catch(()=>null):Promise.resolve(null)]).then(([f,s])=>{if(active){setFunds(f);setState(s);if(ids.length>=2)void run(ids)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user?.id]);
 const matches=useMemo(()=>new Map((state?.matches?.results||[]).map(m=>[m.symbol,m])),[state]);
 async function run(override?:string[]){const arr=(override||selected).filter(validId);if(arr.length<2){setError('Choose at least two funds to compare.');return;}setBusy(true);setError('');try{const data=await rpc<CompareRow[]>('app_compare_investments',{p_investment_ids:arr});setRows(data);history.replaceState(null,'',`/compare?ids=${arr.join(',')}`)}catch(e){setError(e instanceof Error?e.message:'Could not compare these funds.')}finally{setBusy(false)}}
 function setSlot(index:number,value:string){setSelected(current=>current.map((x,i)=>i===index?value:x));}
 return <section className="section"><div className="container"><div className="eyebrow">Compare</div><h1>Compare facts and DNA fit side by side</h1><p className="muted">Choose two or three funds. Fund facts stay primary; your Investor DNA adds a personal compatibility layer when available.</p>
 {loading?<p>Loading comparison tools…</p>:<><div className="compare-picker">{selected.map((id,i)=><label key={i}>Fund {i+1}<select className="field" value={id} onChange={e=>setSlot(i,e.target.value)}><option value="">{i<2?'Choose a fund':'Optional third fund'}</option>{funds.filter(f=>!selected.includes(f.id)||f.id===id).map(f=><option key={f.id} value={f.id}>{f.symbol} — {f.name}</option>)}</select></label>)}</div><div className="actions"><button className="btn primary" disabled={busy} onClick={()=>void run()}>{busy?'Comparing…':'Compare funds'}</button><Link className="btn" href="/screener">Back to screener</Link></div></>}
 {error&&<p className="notice" role="alert">{error}</p>}
 {rows.length>=2&&<><div className="compare-grid">{rows.map(x=>{const m=matches.get(x.symbol);const allocation=x.target_allocation||{};return <article className="compare-card" key={x.id}><div><span className="pill">{x.symbol}</span></div><h2>{x.name}</h2>{m?<div><div className="compare-score">{m.match_score==null?'Review':`${Math.round(m.match_score)}/100`}</div><strong>{fitLabel(m)}</strong><p className="fine muted">Personal compatibility layer</p></div>:<div className="notice"><span>{user?'No ranked DNA fit available':'Sign in with saved DNA to add personal fit'}</span></div>}
 <div className="compare-metric"><span>Official risk</span><strong>{x.risk_level||'Not available'}</strong></div><div className="compare-metric"><span>1-year return</span><strong>{formatMetric(x.return_1y_pct,'%')}</strong></div><div className="compare-metric"><span>3-year annualized</span><strong>{formatMetric(x.return_3y_annualized_pct,'%')}</strong></div><div className="compare-metric"><span>5-year annualized</span><strong>{formatMetric(x.return_5y_annualized_pct,'%')}</strong></div><div className="compare-metric"><span>MER</span><strong>{formatMetric(x.mer_pct,'%')}</strong></div><div className="compare-metric"><span>Distribution yield</span><strong>{formatMetric(x.yield_pct,'%')}</strong></div>{Object.keys(allocation).length?<div className="compare-metric"><span>Strategic allocation</span><strong>{Object.entries(allocation).map(([k,v])=>`${k.replaceAll('_',' ')} ${formatMetric(v,'%')}`).join(' · ')}</strong></div>:null}
 {m?.explanation?.strengths?.length?<><strong>Why it may fit</strong><ul className="compare-fit-list">{m.explanation.strengths.slice(0,2).map(t=><li key={t}>{t}</li>)}</ul></>:null}{m?.explanation?.watchouts?.length?<><strong>What conflicts</strong><ul className="compare-fit-list">{m.explanation.watchouts.slice(0,2).map(t=><li key={t}>{t}</li>)}</ul></>:null}<Link className="btn" href={`/investment/${x.id}`}>Open fund research</Link></article>})}</div><p className="fine muted">Returns are historical and not forecasts. DNA fit is a compatibility signal based on your current saved inputs and the current research data version, not a recommendation to buy.</p></>}
 </div></section>;
}
