// Uses intercepted backend responses. Never sends real email or creates production assessments.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path'),fs=require('node:fs');
const ORIGIN=process.env.TEST_ORIGIN||'http://127.0.0.1:3001';const artifacts=path.join(__dirname,'artifacts');fs.mkdirSync(artifacts,{recursive:true});
const DRAFT_KEY='investing-dna:draft:v2',CLAIM_KEY='investing-dna:claim:v1';
const dna={archetype:'MAVERICK',risk_tolerance:56,risk_capacity:64,model_version:'dna-v1.10-research',calibration_status:'pre_validation',behavioral_profile:{decision_independence:75,long_term_orientation:50,reference_flexibility:67,evidence_discipline:75,emotional_decision_control:50},experience_profile:{role:'context_only',overall_score:66.67,dimensions:{decision_experience:2,product_exposure:2,downturn_experience:2}},quality_profile:{supported:true,consistency_score:83,consistency_label:'high',clarification_recommended:false,conflict_count:0,mixed_count:0},methodology_note:'Pre-validation research output. Questionnaire wording, cut points and response-consistency rules remain provisional until cognitive testing and a real pilot are completed.'};
const questions=[{question_id:'RT01',section:'risk_tolerance',construct:'growth_risk_tradeoff',construct_role:'primary',prompt:'Which balance feels most comfortable?',question_type:'single_choice',options:[{value:'A',label:'Smaller ups and downs'},{value:'B',label:'Moderate ups and downs'},{value:'C',label:'Larger ups and downs'},{value:'D',label:'Very large ups and downs'}]},{question_id:'BD01',section:'behavioral_dna',construct:'decision_independence',construct_role:'primary',prompt:'How much would someone else’s success increase your interest?',question_type:'single_choice',options:[{value:'A',label:'A lot'},{value:'B',label:'Some'},{value:'C',label:'A little'},{value:'D',label:'Not at all'}]}];
const authUser={id:'00000000-0000-0000-0000-000000000001',aud:'authenticated',role:'authenticated',email:'test@example.com',app_metadata:{provider:'email'},user_metadata:{},created_at:new Date().toISOString()};
const jwt=['eyJhbGciOiJIUzI1NiJ9',Buffer.from(JSON.stringify({sub:authUser.id,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'signature'].join('.');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});const ctx=await browser.newContext({viewport:{width:390,height:844}});const page=await ctx.newPage();page.setDefaultTimeout(15000);const runtimeErrors=[];page.on('pageerror',e=>runtimeErrors.push(e.message));let starts=0,claims=0,saved=false,failSave=true,failClaim=true,failEmail=false;
await page.route('https://dna-test.supabase.co/**',async route=>{const req=route.request(),url=req.url(),body=req.postDataJSON()||{};const send=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
 if(url.includes('/auth/v1/otp')){assert.equal(body.email,'test@example.com');return failEmail?send({msg:'Email delivery unavailable'},500):send({});}if(url.includes('/auth/v1/user'))return send(authUser);if(url.includes('/auth/v1/logout'))return send({});if(url.includes('/rest/v1/rpc/app_watchlist'))return send({items:[]});if(url.includes('/rest/v1/rpc/get_current_investor_app_state'))return send({has_profile:true,assessment_id:saved?'assessment-1':null,dna:saved?dna:null,report:saved?dna:null,matches:null});
 if(url.includes('/functions/v1/investing-dna-pilot')){if(body.action==='start'){starts++;assert.equal(body.cohort_code,'DEV_V1_10');assert.match(body.consent_version,/prepilot-v1\.10-en/);return send({assessment_id:'assessment-1',session_token:'guest-capability',account_linked:false,questionnaire_version:'v1.10-cognitive-candidate',model_version:'dna-v1.10-research',language_code:'en'});}if(body.action==='questionnaire')return send({questions,questionnaire_version:'v1.10-cognitive-candidate'});if(body.action==='save_answers'){assert.deepEqual(body.answers,[{question_id:'RT01',answer_value:{value:'C'}},{question_id:'BD01',answer_value:{value:'D'}}]);if(failSave){failSave=false;return send({error:'Temporary save error'},503);}return send({saved:2});}if(body.action==='submit')return send({result:dna,quality:dna.quality_profile,fingerprint:{decision_style:'Balanced',pressure_style:'Measured',strengths:['decision_independence'],watchouts:[]},report:{report:{...dna,decision_style:'Balanced',pressure_style:'Measured'}},account_linked:false});if(body.action==='claim_assessment'){claims++;assert.equal(req.headers().authorization,'Bearer '+jwt);if(failClaim){failClaim=false;return send({error:'Temporary claim error'},503);}saved=true;return send({claimed:true});}}
 throw Error('Unexpected request: '+url);});
const check=name=>console.log('PASS '+name);
await page.goto(ORIGIN+'/dna/assessment');await page.getByRole('button',{name:'Start as guest'}).waitFor();assert.match(await page.locator('body').innerText(),/28 questions/);await page.getByRole('button',{name:'Start as guest'}).click();await page.getByRole('button',{name:'Larger ups and downs',exact:true}).click();await page.getByRole('button',{name:'Next',exact:true}).click();await page.reload();await page.getByRole('heading',{name:'How much would someone else’s success increase your interest?'}).waitFor();assert.equal(starts,1);check('refresh resumes canonical v1.10 assessment without a second session');
await page.getByRole('button',{name:'Not at all',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Larger ups and downs',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Next',exact:true}).click();check('back navigation preserves v1.10 answers');
await page.getByRole('button',{name:'See my DNA'}).click();await page.getByRole('alert').filter({hasText:'Temporary save error'}).waitFor();await page.getByRole('button',{name:'See my DNA'}).click();await page.waitForURL('**/dna/result');await page.getByRole('heading',{name:'MAVERICK'}).waitFor();const resultText=await page.locator('body').innerText();assert.match(resultText,/Risk tolerance/);assert.match(resultText,/Financial capacity/);assert.match(resultText,/Your decision fingerprint/);assert.match(resultText,/research candidate/i);assert.equal(await page.evaluate(k=>localStorage.getItem(k),DRAFT_KEY),null);assert.ok(await page.evaluate(k=>localStorage.getItem(k),CLAIM_KEY));check('submission retry lands on ephemeral v1.10 result and retains only a claim ticket');
await page.getByLabel('Or send me a secure save link').fill('test@example.com');failEmail=true;await page.getByRole('button',{name:'Email me the link'}).click();await page.getByRole('alert').filter({hasText:'Email delivery unavailable'}).waitFor();failEmail=false;await page.getByRole('button',{name:'Email me the link'}).click();await page.getByRole('status').filter({hasText:'Check your email'}).waitFor();check('result distinguishes email failure from secure-link success');
await page.getByRole('link',{name:'Create free account',exact:true}).click();await page.waitForURL('**/profile?mode=signup');const callback=ORIGIN+'/profile?save=dna#access_token='+encodeURIComponent(jwt)+'&refresh_token='+encodeURIComponent('fake-refresh-token')+'&expires_in=3600&token_type=bearer&type=magiclink';await page.goto(callback);await page.getByRole('button',{name:'Save this DNA to my account'}).waitFor();await page.getByRole('button',{name:'Save this DNA to my account'}).click();await page.getByRole('alert').filter({hasText:'Temporary claim error'}).waitFor();assert.ok(await page.evaluate(k=>localStorage.getItem(k),CLAIM_KEY));await page.getByRole('button',{name:'Save this DNA to my account'}).click();await page.getByRole('heading',{name:'MAVERICK'}).waitFor();assert.equal(claims,2);assert.equal(await page.evaluate(k=>localStorage.getItem(k),CLAIM_KEY),null);check('magic-link callback claims DNA safely and clears the claim ticket after saved profile reloads server DNA');
await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByLabel('Email address').waitFor();check('sign out clears personal profile view');await page.screenshot({path:path.join(artifacts,'assessment-v110-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(runtimeErrors,[]);check('canonical assessment flow has no browser runtime errors');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
