const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path');
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:3001';const artifacts=path.join(__dirname,'artifacts');fs.mkdirSync(artifacts,{recursive:true});
const id='efbc71a7-d6c7-451c-afb8-1dfee261441d',id2='48580aac-8147-4054-b99f-5d696ce3ceca',assessmentId='11111111-1111-4111-8111-111111111111';
const shared={capital_protection:'none',liquidity_level:'high',price_volatility:'low',income_predictability:'high',growth_participation:'low',interest_rate_sensitivity:'medium',diversification_level:'diversified',complexity_level:'medium',time_structure:'open_ended',structure_as_of_date:'2026-09-10'};
const fund={...shared,id,symbol:'ZAG',name:'BMO Aggregate Bond Index ETF',asset_type:'ETF',currency:'CAD',issuer_name:'BMO Global Asset Management',price:null,return_1y_pct:4.21,return_3y_annualized_pct:3.18,return_5y_annualized_pct:2.44,mer_pct:0.08,yield_pct:3.71,aum:9200000000,risk_level:'Low to Medium',data_status:'verified_partial',profile_summary:'Diversified Canadian investment-grade bonds.',profile_objective:'Income and broad bond exposure.',profile_benchmark:'Canadian bond index',profile_key_risks:['Interest-rate risk','Credit risk'],profile_target_allocation:{equity:0,fixed_income:100}};
const fund2={...shared,id:id2,symbol:'VBAL',name:'Vanguard Balanced ETF Portfolio',asset_type:'ETF',currency:'CAD',issuer_name:'Vanguard Canada',price:35.2,return_1y_pct:13.89,return_3y_annualized_pct:13.73,return_5y_annualized_pct:7.77,mer_pct:0.24,yield_pct:2.1,aum:4200000000,risk_level:'Low to Medium',data_status:'verified_partial',profile_summary:'A globally diversified balanced portfolio.',profile_target_allocation:{equity:60,fixed_income:40}};
const research={investment_id:id,coverage:{has_official_facts:true,has_official_risk:true,has_return_1y:true,has_return_3y:true,has_return_5y:true,has_portfolio_characteristics:true,has_complete_exposure_set:false,has_full_holdings_detail:false,holdings_weight_coverage_pct:7.46,data_status:'verified_partial'},performance:{return_1y_pct:4.21,return_3y_annualized_pct:3.18,return_5y_annualized_pct:2.44,return_1y_as_of_date:'2026-08-31',return_3y_as_of_date:'2026-08-31',return_5y_as_of_date:'2026-08-31',return_1y_verification_status:'issuer_linked',return_3y_verification_status:'issuer_linked',return_5y_verification_status:'issuer_linked'},characteristics:{number_of_bonds:1200,yield_to_maturity_pct:3.9,average_duration_years:7.1,average_credit_quality:'AA'},holdings:{mode:'top_holdings_sample',as_of_date:'2026-08-31',weight_coverage_pct:7.46,known_underlying_weight_pct:0,items:[{holding_symbol:'CAN-GOV',holding_name:'Government of Canada',weight_pct:4.2,asset_type:'bond',sector:'Government Bonds'}]}};
const research2={investment_id:id2,coverage:{has_official_facts:true,has_official_risk:true,has_return_1y:true,has_return_3y:true,has_return_5y:true,has_full_holdings_detail:true,holdings_weight_coverage_pct:99.97,data_status:'verified_partial'},performance:{return_1y_pct:13.89,return_3y_annualized_pct:13.73,return_5y_annualized_pct:7.77,return_1y_as_of_date:'2026-09-10',return_3y_as_of_date:'2026-07-31',return_5y_as_of_date:'2026-07-31',return_1y_verification_status:'issuer_linked',return_3y_verification_status:'issuer_linked',return_5y_verification_status:'issuer_linked'},characteristics:{number_of_stocks:13725,number_of_bonds:17230},holdings:{mode:'fund_of_funds_structure',as_of_date:'2026-08-31',weight_coverage_pct:99.97,known_underlying_weight_pct:84.54,items:[]}};
const user={id:'00000000-0000-0000-0000-000000000001',aud:'authenticated',role:'authenticated',email:'test@example.com',app_metadata:{provider:'email'},user_metadata:{},created_at:new Date().toISOString()};
const testAccess=['eyJhbGciOiJIUzI1NiJ9',Buffer.from(JSON.stringify({sub:user.id,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'signature'].join('.');
const dna={archetype:'MAVERICK',risk_tolerance:56,risk_capacity:64,model_version:'dna-v1.10-research'};
const goalFit={model_version:'goal-fit-v1',score:84,components:{growth:.5,stability:.35,liquidity:.15},summary:'Major purchase uses a horizon-sensitive balance of growth, stability and liquidity without treating the purchase goal as guaranteed capital.'};
const match1={investment_id:id,symbol:fund.symbol,name:fund.name,match_score:82,eligibility:'eligible',recommendation_tier:'alternative',risk_band:'Low to Medium',explanation:{fit_label:'Possible fit',summary:'Research compatibility, subject to the limits below.',strengths:['Official risk is aligned.'],watchouts:['Bond prices can fall as rates change.'],scores:{official_risk_fit:92,market_exposure_fit:100,goal_role_fit:78,exposure_breadth:70},goal_fit:goalFit}};
const match2={investment_id:id2,symbol:fund2.symbol,name:fund2.name,match_score:88,eligibility:'eligible',recommendation_tier:'top_match',risk_band:'Low to Medium',explanation:{fit_label:'Closer fit',summary:'Research compatibility, subject to the limits below.',strengths:['Equity exposure is within your limit.'],watchouts:['Equity markets can decline.'],scores:{official_risk_fit:92,market_exposure_fit:95,goal_role_fit:88,exposure_breadth:86},goal_fit:goalFit}};
const dnaOnly=item=>({...item,match_score:null,eligibility:'context_required',recommendation_tier:'consider',explanation:{...item.explanation,fit_label:'DNA-only comparison',summary:'Add the goal, horizon and capital needs for this money before using a numeric Match score.',goal_fit:null,scores:{...item.explanation.scores,goal_role_fit:null}}});
const dnaOnly1=dnaOnly(match1),dnaOnly2=dnaOnly(match2);
let contextReady=false;
function state(hasDna){
 const results=contextReady?[match2,match1]:[dnaOnly2,dnaOnly1];
 return {has_profile:true,assessment_id:hasDna?assessmentId:undefined,dna:hasDna?dna:null,report:hasDna?{...dna,...(contextReady?{investment_context:{goal:'major_purchase',time_horizon:'gt_10y',liquidity_need:'low',principal_required:'no'}}:{})}:null,matches:hasDna?{status:contextReady?'available':'context_required',model_version:'investment-dna-match-v7',goal_model_version:'goal-fit-v1',eligible_count:contextReady?2:0,data_as_of:'2026-09-10',results,top_matches:contextReady?[match2]:[],alternatives:contextReady?[match1]:[],consider:contextReady?[]:[dnaOnly2,dnaOnly1],mismatch:[]}:null};
}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
 let saved=false,hasDna=false,failDetail=true,failSave=true,otp=false;const errors=[],tracked=[];
 const ctx=await browser.newContext({viewport:{width:390,height:844}});
 await ctx.route('https://dna-test.supabase.co/**',async route=>{const req=route.request(),url=req.url(),body=req.postDataJSON()||{};const send=(d,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(d)});
  if(url.includes('/functions/v1/investing-dna-pilot')&&body.action==='track_event'){tracked.push(body.event_name);return send({tracked:true});}
  if(url.includes('/auth/v1/otp')){assert.equal(body.create_user,true);assert.equal(body.email,'test@example.com');assert.equal(new URL(url).searchParams.get('redirect_to'),origin+'/profile?investment='+id);otp=true;return send({});}
  if(url.includes('/auth/v1/user'))return send(user);if(url.includes('/auth/v1/logout'))return send({});
  if(url.includes('/rpc/app_search_instruments'))return send([fund,fund2]);
  if(url.includes('/rpc/app_market_data_status')){
   const ids=body.p_investment_ids||[];
   return send(ids.map(investment_id=>investment_id===id?{investment_id,latest_price:62.34,previous_price:61.9,daily_change_pct:.711,volume:184200,currency:'CAD',price_date:'2026-09-18',source_key:'yahoo_free',source_name:'Yahoo Finance (temporary free research feed)',ingested_at:'2026-09-19T01:40:00Z'}:investment_id===id2?{investment_id,latest_price:35.44,previous_price:35.31,daily_change_pct:.368,volume:99300,currency:'CAD',price_date:'2026-09-18',source_key:'yahoo_free',source_name:'Yahoo Finance (temporary free research feed)',ingested_at:'2026-09-19T01:40:00Z'}:null).filter(Boolean));
  }
  if(url.includes('/rpc/app_search_investments'))return send([fund,fund2]);
  if(url.includes('/rpc/app_get_investment_research_context'))return send(body.p_investment_id===id?research:body.p_investment_id===id2?research2:null);
  if(url.includes('/rpc/app_get_investment_dna'))return send(null);if(url.includes('/rpc/app_get_official_fund_facts'))return send(null);
  if(url.includes('/rpc/app_get_product_risk'))return send({status:'not_available',reason:'No calibrated Product Risk DNA profile has been published for this investment.'});
  if(url.includes('/rpc/app_get_instrument')){const found=body.p_investment_id===id?fund:body.p_investment_id===id2?fund2:null;if(body.p_investment_id===id&&failDetail)return send({message:'Temporary detail error'},503);return send(found);}
  if(url.includes('/rpc/app_compare_instruments')){const ids=body.p_investment_ids||[];return send(ids.map(x=>x===id?fund:x===id2?fund2:null).filter(Boolean));}
  if(url.includes('/rpc/app_watchlist')){assert.ok(req.headers().authorization);if(body.p_action==='list')return send({items:saved?[{investment_id:id,symbol:fund.symbol,name:fund.name}]:[]});if(body.p_action==='add'){if(failSave){failSave=false;return send({message:'Temporary watchlist error'},503);}saved=true;return send({item:{investment_id:id}});}if(body.p_action==='remove'){saved=false;return send({removed:true});}}
  if(url.includes('/rpc/app_open_returning_workspace'))return send({has_profile:true,returning:true,previous_seen_at:'2026-09-17T20:00:00Z',previous_market_date:'2026-09-17',current_market_date:'2026-09-18',watchlist_count:saved?1:0,watchlist_changed:false,new_market_data_count:saved?1:0,updated_saved_items:saved?[{investment_id:id,symbol:fund.symbol,name:fund.name,price_date:'2026-09-18',latest_price:62.34,daily_change_pct:.711,currency:'CAD'}]:[],match_updated:false,assessment_changed:false});
  if(url.includes('/rpc/app_investment_fit'))return send(hasDna?{status:'available',run_id:'run-1',fit:contextReady?match1:dnaOnly1}:{status:'no_dna'});
  if(url.includes('/rpc/app_save_current_investment_context')){assert.equal(body.p_context.goal,'major_purchase');assert.equal(body.p_context.time_horizon,'gt_10y');assert.equal(body.p_context.liquidity_need,'low');assert.equal(body.p_context.principal_required,'no');contextReady=true;return send({report:{report:state(true).report},match:state(true).matches});}
  if(url.includes('/rpc/get_current_investor_app_state'))return send(state(hasDna));
  throw Error('Unexpected request '+url);
 });
 let page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));const check=n=>console.log('PASS '+n);
 await page.goto(origin+'/explore');await page.getByText('Price updated after close · Sep 18, 2026',{exact:true}).first().waitFor();await page.getByRole('link',{name:'Open research',exact:true}).first().click();await page.getByRole('heading',{name:'Could not load this investment'}).waitFor();failDetail=false;await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('heading',{name:fund.name,exact:true}).waitFor();check('ETF navigation uses the generic research read model and handles retry');
 await page.getByRole('button',{name:'Performance & holdings',exact:true}).click();const detailText=await page.locator('body').innerText();assert.match(detailText,/Market data after close/i);assert.match(detailText,/Sep 18, 2026/i);assert.match(detailText,/62\.34/);assert.match(detailText,/Verified performance history/i);assert.match(detailText,/Top holdings available/i);assert.match(detailText,/0\.08%/);assert.match(detailText,/AA/);check('ETF detail preserves fund-specific research behind mobile progressive disclosure');
 await page.locator('.mobile-detail-actions a[href^="/profile?mode=signup&investment="]').click();await page.getByRole('heading',{name:'Create your free account or sign in'}).waitFor();await page.getByLabel('Email address').fill('test@example.com');await page.getByRole('button',{name:'Email me a secure link'}).click();await page.getByRole('heading',{name:'Check your email',exact:true}).waitFor();await page.getByText('Keep this tab open.',{exact:true}).waitFor();assert.match(await page.locator('.auth-browser-note').innerText(),/same device and browser/i);const resendButton=page.getByRole('button',{name:/Send again in \d+s/});await resendButton.waitFor();assert.equal(await resendButton.isDisabled(),true);await page.getByRole('button',{name:'Use a different email',exact:true}).waitFor();await page.getByRole('status').filter({hasText:'Use the newest email link only'}).waitFor();assert.ok(otp);check('optional registration preserves investment intent and exposes same-browser resend recovery');
 const callback=origin+'/profile?investment='+id+'#access_token='+encodeURIComponent(testAccess)+'&refresh_token='+encodeURIComponent('test-refresh')+'&expires_in=3600&token_type=bearer&type=magiclink';await page.close();page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.goto(callback);await page.getByRole('button',{name:'Save to watchlist',exact:true}).waitFor();await page.getByRole('button',{name:'Save to watchlist',exact:true}).click();await page.getByRole('alert').filter({hasText:'Temporary watchlist error'}).waitFor();await page.getByRole('button',{name:'Save to watchlist',exact:true}).click();await page.getByRole('status').filter({hasText:'ZAG is saved'}).waitFor();assert.ok(saved);check('account continuity and watchlist retry preserve generic investment intent');
 hasDna=true;contextReady=false;
 await page.goto(origin+'/match');await page.getByText('DNA-only view',{exact:true}).waitFor();let bodyText=await page.locator('body').innerText();assert.match(bodyText,/DNA-only comparison/i);assert.doesNotMatch(bodyText,/82\/100|88\/100/);assert.doesNotMatch(await page.locator('.match-score').first().innerText(),/Review/i);assert.equal(await page.locator('.match-breakdown').count(),0);check('contextless Match hides numeric and component scores without mislabeling DNA-only rows as review');
 await page.goto(origin+'/investment/'+id);await page.getByRole('button',{name:'Save & official documents',exact:true}).click();await page.getByText('DNA-only comparison',{exact:true}).waitFor();assert.equal((await page.locator('.kpi').last().innerText()).trim(),'DNA-only');check('ETF detail keeps context-required compatibility explicitly DNA-only');
 await page.goto(origin+'/screener');await page.getByText('Your DNA is connected.').waitFor();bodyText=await page.locator('body').innerText();assert.match(bodyText,/Numeric Match scores stay hidden/i);assert.match(bodyText,/DNA-only/i);assert.doesNotMatch(bodyText,/82\/100|88\/100/);check('screener preserves DNA-only semantics before investment context');
 await page.goto(origin+`/compare?ids=${id},${id2}`);await page.getByRole('heading',{name:'Compare investments',exact:true}).waitFor();await page.getByRole('heading',{name:fund.name,exact:true}).waitFor();await page.getByRole('heading',{name:fund2.name,exact:true}).waitFor();bodyText=await page.locator('body').innerText();assert.match(bodyText,/DNA-only/);assert.match(bodyText,/DNA-only comparison/i);assert.doesNotMatch(bodyText,/82\/100|88\/100/);assert.doesNotMatch(bodyText,/\bReview\b/);check('contextless Compare uses DNA-only semantics instead of falsely labeling missing scores as review');
 await page.goto(origin+'/match');await page.getByText('DNA-only view',{exact:true}).waitFor();await page.getByRole('link',{name:'Add investment context'}).first().click();await page.waitForURL(url=>url.pathname==='/dna/context'&&url.searchParams.get('returnTo')==='/match');await page.getByRole('heading',{name:'Let’s put your DNA into action.'}).waitFor();const goal=page.getByLabel('Investment goal');assert.equal(await goal.locator('option[value="wealth_preservation"]').count(),1);assert.equal(await goal.locator('option[value="major_purchase"]').count(),1);await goal.selectOption('major_purchase');await page.getByLabel('When might you first need this money?').selectOption('gt_10y');await page.getByLabel('How important is quick access?').selectOption('low');await page.getByLabel('At the time you need it, must the full amount be protected from investment loss?').selectOption('no');await page.getByRole('button',{name:'See my personalized insights'}).click();await page.waitForURL(url=>url.pathname==='/match');await page.getByText('Context-aware match',{exact:true}).waitFor();assert.ok(contextReady);assert.match(await page.locator('body').innerText(),/88\/100/);check('investment context exposes all v7 goals and returns the same account directly to numeric context-aware Match');
 await page.goto(origin+'/investment/'+id);await page.getByRole('button',{name:'Save & official documents',exact:true}).click();await page.getByText('Possible fit',{exact:true}).waitFor();assert.match(await page.locator('body').innerText(),/82\/100/);check('ETF detail displays canonical v7 context-aware DNA compatibility');
 await page.goto(origin+'/match');await page.getByText('Context-aware match',{exact:true}).waitFor();await page.locator('.match-context-summary').click();bodyText=await page.locator('body').innerText();assert.match(bodyText,/What this Match is using/i);assert.match(bodyText,/Major purchase/i);assert.match(bodyText,/More than 10 years/i);assert.match(bodyText,/Low — can stay invested/i);assert.match(bodyText,/No — market loss can be accepted at that time/i);assert.match(bodyText,/How this goal changes Match/i);assert.match(bodyText,/Major purchase uses a horizon-sensitive balance of growth, stability and liquidity/i);assert.match(bodyText,/Risk level/i);assert.match(bodyText,/Equity exposure/i);assert.match(bodyText,/Goal fit/i);assert.match(bodyText,/Diversification/i);assert.match(bodyText,/What could change the fit/i);assert.match(bodyText,/What to watch/i);assert.match(bodyText,/Match model investment-dna-match-v7/i);assert.doesNotMatch(bodyText,/Research compatibility, subject to the limits below/i);await page.getByRole('link',{name:'Open ETF research',exact:true}).first().click();await page.getByRole('heading',{name:fund2.name,exact:true}).waitFor();check('Match v7 makes money context and goal-specific explanation visible before linking to ETF research');
 await page.goto(origin+'/screener');await page.getByRole('heading',{name:'ETF Screener',exact:true}).waitFor();await page.getByText('Your DNA is connected.').waitFor();assert.match(await page.locator('body').innerText(),/88\/100/);const boxes=page.getByRole('checkbox');await boxes.nth(0).check();await boxes.nth(1).check();await page.getByRole('link',{name:'Compare selected'}).click();await page.getByRole('heading',{name:'Compare investments',exact:true}).waitFor();await page.getByRole('heading',{name:fund.name,exact:true}).waitFor();await page.getByRole('heading',{name:fund2.name,exact:true}).waitFor();const compareText=await page.locator('body').innerText();assert.match(compareText,/82\/100/);assert.match(compareText,/88\/100/);assert.match(compareText,/Shared Investment DNA/i);check('ETF screener selection flows into structure-first comparison without losing v7 fit');
 await page.goto(origin+'/profile');await page.getByRole('heading',{name:'Your investing workspace',exact:true}).waitFor();assert.match(await page.locator('body').innerText(),/VBAL/);assert.match(await page.locator('body').innerText(),/saved investment/i);check('returning profile uses asset-neutral research language');
 await page.goto(origin+'/');await page.getByRole('heading',{name:'Welcome back',exact:true}).waitFor();let homeText=await page.locator('.home-returning-workspace').innerText();assert.match(homeText,/MAVERICK/);assert.match(homeText,/1 saved/);assert.match(homeText,/VBAL · 88\/100/);assert.match(homeText,/New market data is ready for 1 saved investment/);assert.match(homeText,/Previous workspace visit/);await page.reload();await page.getByRole('heading',{name:'Welcome back',exact:true}).waitFor();homeText=await page.locator('.home-returning-workspace').innerText();assert.match(homeText,/MAVERICK/);assert.match(homeText,/1 saved/);check('signed-in home survives reload and restores DNA, goal, Match and watchlist continuity');
 await page.goto(origin+'/watchlist');await page.getByRole('heading',{name:'Your watchlist',exact:true}).waitFor();await page.getByRole('button',{name:'Remove',exact:true}).click();await page.getByRole('heading',{name:'Your watchlist is empty',exact:true}).waitFor();
 for(const event of ['app_session_started','explore_viewed','fund_viewed','signup_requested','secure_link_requested','watchlist_saved','watchlist_removed','profile_viewed','workspace_viewed','match_viewed','screener_viewed','compare_viewed'])assert.ok(tracked.includes(event),`missing analytics event ${event}`);check('pilot funnel events still fire across signup, save/remove and the connected product loop');
 await page.screenshot({path:path.join(artifacts,'milestone2-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);check('connected ETF flow remains mobile-safe with no runtime errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});