const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path');
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:3001';const artifacts=path.join(__dirname,'artifacts');fs.mkdirSync(artifacts,{recursive:true});
const id='efbc71a7-d6c7-451c-afb8-1dfee261441d',id2='48580aac-8147-4054-b99f-5d696ce3ceca';
const fund={id,symbol:'ZAG',name:'BMO Aggregate Bond Index ETF',asset_type:'ETF',currency:'CAD',issuer_name:'BMO Global Asset Management',price:null,return_1y_pct:4.21,return_3y_annualized_pct:3.18,return_5y_annualized_pct:2.44,mer_pct:0.08,yield_pct:3.71,aum:9200000000,risk_level:'Low to Medium',data_status:'verified_partial',profile_summary:'Diversified Canadian investment-grade bonds.',profile_objective:'Income and broad bond exposure.',profile_benchmark:'Canadian bond index',profile_key_risks:['Interest-rate risk','Credit risk'],profile_target_allocation:{equity:0,fixed_income:100}};
const fund2={id:id2,symbol:'VBAL',name:'Vanguard Balanced ETF Portfolio',asset_type:'ETF',currency:'CAD',issuer_name:'Vanguard Canada',price:35.2,return_1y_pct:13.89,return_3y_annualized_pct:13.73,return_5y_annualized_pct:7.77,mer_pct:0.24,yield_pct:2.1,aum:4200000000,risk_level:'Low to Medium',data_status:'verified_partial',profile_summary:'A globally diversified balanced portfolio.',profile_target_allocation:{equity:60,fixed_income:40}};
const research={investment_id:id,coverage:{has_official_facts:true,has_official_risk:true,has_return_1y:true,has_return_3y:true,has_return_5y:true,has_portfolio_characteristics:true,has_complete_exposure_set:false,has_full_holdings_detail:false,holdings_weight_coverage_pct:7.46,data_status:'verified_partial'},performance:{return_1y_pct:4.21,return_3y_annualized_pct:3.18,return_5y_annualized_pct:2.44,return_1y_as_of_date:'2026-08-31',return_3y_as_of_date:'2026-08-31',return_5y_as_of_date:'2026-08-31',return_1y_verification_status:'issuer_linked',return_3y_verification_status:'issuer_linked',return_5y_verification_status:'issuer_linked'},characteristics:{number_of_bonds:1200,yield_to_maturity_pct:3.9,average_duration_years:7.1,average_credit_quality:'AA'},holdings:{mode:'top_holdings_sample',as_of_date:'2026-08-31',weight_coverage_pct:7.46,known_underlying_weight_pct:0,items:[{holding_symbol:'CAN-GOV',holding_name:'Government of Canada',weight_pct:4.2,asset_type:'bond',sector:'Government Bonds'}]}};
const research2={investment_id:id2,coverage:{has_official_facts:true,has_official_risk:true,has_return_1y:true,has_return_3y:true,has_return_5y:true,has_full_holdings_detail:true,holdings_weight_coverage_pct:99.97,data_status:'verified_partial'},performance:{return_1y_pct:13.89,return_3y_annualized_pct:13.73,return_5y_annualized_pct:7.77,return_1y_as_of_date:'2026-09-10',return_3y_as_of_date:'2026-07-31',return_5y_as_of_date:'2026-07-31',return_1y_verification_status:'issuer_linked',return_3y_verification_status:'issuer_linked',return_5y_verification_status:'issuer_linked'},characteristics:{number_of_stocks:13725,number_of_bonds:17230},holdings:{mode:'fund_of_funds_structure',as_of_date:'2026-08-31',weight_coverage_pct:99.97,known_underlying_weight_pct:84.54,items:[{holding_symbol:'VUN',holding_name:'Vanguard U.S. Total Market Index ETF',weight_pct:27.37,asset_type:'ETF',known_investment_id:id,known_investment_name:fund.name}]}};
const user={id:'00000000-0000-0000-0000-000000000001',aud:'authenticated',role:'authenticated',email:'test@example.com',app_metadata:{provider:'email'},user_metadata:{},created_at:new Date().toISOString()};
const jwt=['eyJhbGciOiJIUzI1NiJ9',Buffer.from(JSON.stringify({sub:user.id,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'signature'].join('.');
const session={access_token:jwt,refresh_token:'fake-refresh-token',token_type:'bearer',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,user};
const match1={investment_id:id,symbol:fund.symbol,name:fund.name,match_score:82,eligibility:'eligible',recommendation_tier:'alternative',risk_band:'Low to Medium',explanation:{fit_label:'Possible fit',summary:'Research compatibility, subject to the limits below.',strengths:['Official risk is aligned.'],watchouts:['Bond prices can fall as rates change.'],scores:{official_risk_fit:92,market_exposure_fit:100,goal_role_fit:78,exposure_breadth:70}}};
const match2={investment_id:id2,symbol:fund2.symbol,name:fund2.name,match_score:88,eligibility:'eligible',recommendation_tier:'top_match',risk_band:'Low to Medium',explanation:{fit_label:'Closer fit',summary:'Research compatibility, subject to the limits below.',strengths:['Equity exposure is within your limit.'],watchouts:['Equity markets can decline.'],scores:{official_risk_fit:92,market_exposure_fit:95,goal_role_fit:88,exposure_breadth:86}}};
function state(hasDna){return {has_profile:true,dna:hasDna?{archetype:'MAVERICK',risk_tolerance:56,risk_capacity:64}:null,report:hasDna?{investment_context:{goal:'retirement',time_horizon:'10_plus',liquidity_need:'low'}}:null,matches:hasDna?{status:'available',model_version:'investment-dna-match-v6',eligible_count:2,data_as_of:'2026-09-10',results:[match2,match1],top_matches:[match2],alternatives:[match1],consider:[],mismatch:[]}:null};}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
let saved=false,hasDna=false,failDetail=true,failSave=true,otp=false;const errors=[];
async function setup(context){await context.route('https://dna-test.supabase.co/**',async route=>{const req=route.request(),url=req.url(),body=req.postDataJSON()||{};const send=(d,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(d)});
 if(url.includes('/auth/v1/otp')){assert.equal(body.create_user,true);assert.equal(body.email,'test@example.com');assert.equal(new URL(url).searchParams.get('redirect_to'),origin+'/profile?investment='+id);otp=true;return send({});}
 if(url.includes('/auth/v1/user'))return send(user);if(url.includes('/auth/v1/logout'))return send({});
 if(url.includes('/rpc/app_search_investments'))return send([fund,fund2]);
 if(url.includes('/rpc/app_get_investment_research_context'))return send(body.p_investment_id===id?research:body.p_investment_id===id2?research2:null);
 if(url.includes('/rpc/app_get_investment_dna'))return send(null);if(url.includes('/rpc/app_get_official_fund_facts'))return send(null);
 if(url.includes('/rpc/app_get_investment')){const found=body.p_investment_id===id?fund:body.p_investment_id===id2?fund2:null;if(body.p_investment_id===id&&failDetail){return send({message:'Temporary detail error'},503);}return send(found);}
 if(url.includes('/rpc/app_compare_investments')){const ids=body.p_investment_ids||[];return send(ids.map(x=>x===id?fund:x===id2?fund2:null).filter(Boolean));}
 if(url.includes('/rpc/app_watchlist')){assert.equal(req.headers().authorization,'Bearer '+jwt);assert.equal(body.p_profile_id,undefined);if(body.p_action==='list')return send({items:saved?[{investment_id:id,symbol:fund.symbol,name:fund.name}]:[]});if(body.p_action==='add'){if(failSave){failSave=false;return send({message:'Temporary watchlist error'},503);}saved=true;return send({item:{investment_id:id}});}if(body.p_action==='remove'){saved=false;return send({removed:true});}}
 if(url.includes('/rpc/app_investment_fit'))return send(hasDna?{status:'available',run_id:'run-1',fit:match1}:{status:'no_dna'});
 if(url.includes('/rpc/get_current_investor_app_state'))return send(state(hasDna));
 throw Error('Unexpected request '+url);
});}
const ctx=await browser.newContext({viewport:{width:390,height:844}});await setup(ctx);const page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));const check=n=>console.log('PASS '+n);
await page.goto(origin+'/explore');await page.getByRole('link',{name:'View fund',exact:true}).first().click();await page.getByRole('heading',{name:'Could not load this fund'}).waitFor();failDetail=false;await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('heading',{name:fund.name,exact:true}).waitFor();check('fund navigation handles detail error and retry');
const detailText=await page.locator('body').innerText();assert.match(detailText,/Verified performance history/);assert.match(detailText,/Top holdings available/);assert.match(detailText,/Issuer linked/);assert.match(detailText,/0\.08%/);assert.match(detailText,/AA/);check('fund detail separates verified history, partial holdings coverage and portfolio characteristics');
await page.getByRole('link',{name:'Create a free account',exact:true}).click();await page.getByRole('heading',{name:'Create your free account'}).waitFor();await page.getByLabel('Email address').fill('test@example.com');await page.getByRole('button',{name:'Create my free account'}).click();await page.getByRole('status').filter({hasText:'confirm your free account'}).waitFor();assert.ok(otp);check('optional registration preserves fund intent');
await page.evaluate(s=>localStorage.setItem('sb-dna-test-auth-token',JSON.stringify(s)),session);await page.reload();await page.getByRole('button',{name:'Save this fund to my watchlist',exact:true}).click();await page.getByRole('alert').filter({hasText:'Temporary watchlist error'}).waitFor();await page.getByRole('button',{name:'Save this fund to my watchlist',exact:true}).click();await page.getByRole('status').filter({hasText:'ZAG is saved'}).waitFor();assert.ok(saved);check('watchlist retry persists selected fund');
hasDna=true;await page.goto(origin+'/investment/'+id);await page.getByText('Possible fit',{exact:true}).waitFor();assert.match(await page.locator('body').innerText(),/82 \/ 100/);check('fund page displays canonical v6 DNA compatibility');
await page.goto(origin+'/match');await page.getByRole('heading',{name:'Your closest compatible structures'}).waitFor();assert.match(await page.locator('body').innerText(),/Context-aware match/);assert.match(await page.locator('body').innerText(),/What would change this comparison/);await page.getByRole('link',{name:'View Investment DNA',exact:true}).first().click();await page.getByRole('heading',{name:fund2.name,exact:true}).waitFor();check('Match explains compatibility and links to fund research');
await page.goto(origin+'/screener');await page.getByRole('heading',{name:'Find funds, then see how they relate to you'}).waitFor();assert.match(await page.locator('body').innerText(),/88\/100/);const boxes=page.getByRole('checkbox');await boxes.nth(0).check();await boxes.nth(1).check();await page.getByRole('link',{name:'Compare selected'}).click();await page.getByRole('heading',{name:'Compare facts and DNA fit side by side'}).waitFor();await page.getByRole('heading',{name:fund.name,exact:true}).waitFor();await page.getByRole('heading',{name:fund2.name,exact:true}).waitFor();const compareText=await page.locator('body').innerText();assert.match(compareText,/82\/100/);assert.match(compareText,/88\/100/);assert.match(compareText,/3-year annualized/);check('DNA screener selection flows into fact-first side-by-side comparison');
await page.goto(origin+'/profile');await page.getByText('Continue where you left off',{exact:true}).waitFor();assert.match(await page.locator('body').innerText(),/VBAL/);check('returning profile surfaces a concrete next step');
await page.screenshot({path:path.join(artifacts,'milestone2-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('milestone 2 connected flow fits mobile viewport');assert.deepEqual(errors,[]);check('no browser runtime errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
