const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path');
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:3001';const artifacts=path.join(__dirname,'artifacts');fs.mkdirSync(artifacts,{recursive:true});
const id='efbc71a7-d6c7-451c-afb8-1dfee261441d';
const fund={id,symbol:'ZAG',name:'BMO Aggregate Bond Index ETF',asset_type:'ETF',currency:'CAD',issuer_name:'BMO Global Asset Management',price:null,return_1y_pct:null,mer_pct:'0.08',data_status:'identity_only',profile_summary:'Diversified Canadian investment-grade bonds.',profile_objective:'Income and broad bond exposure.',profile_benchmark:'Canadian bond index',profile_key_risks:['Interest-rate risk','Credit risk'],profile_target_allocation:{equity:0,fixed_income:100}};
const user={id:'00000000-0000-0000-0000-000000000001',aud:'authenticated',role:'authenticated',email:'test@example.com',app_metadata:{provider:'email'},user_metadata:{},created_at:new Date().toISOString()};
const jwt=['eyJhbGciOiJIUzI1NiJ9',Buffer.from(JSON.stringify({sub:user.id,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'signature'].join('.');
const session={access_token:jwt,refresh_token:'fake-refresh-token',token_type:'bearer',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,user};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});
let saved=false,hasDna=false,failDetail=true,failSave=true,otp=false;const errors=[];
async function setup(context){await context.route('https://dna-test.supabase.co/**',async route=>{const req=route.request(),url=req.url(),body=req.postDataJSON()||{};const send=(d,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(d)});
 if(url.includes('/auth/v1/otp')){assert.equal(body.create_user,true);assert.equal(body.email,'test@example.com');assert.equal(new URL(url).searchParams.get('redirect_to'),origin+'/profile?investment='+id);otp=true;return send({});}
 if(url.includes('/auth/v1/user'))return send(user);if(url.includes('/auth/v1/logout'))return send({});
 if(url.includes('/rpc/app_search_investments'))return send([fund]);
 if(url.includes('/rpc/app_get_investment')){if(body.p_investment_id!==id)return send(null);if(failDetail){return send({message:'Temporary detail error'},503);}return send(fund);}
 if(url.includes('/rpc/app_watchlist')){assert.equal(req.headers().authorization,'Bearer '+jwt);assert.equal(body.p_profile_id,undefined);if(body.p_action==='list')return send({items:saved?[{investment_id:id,symbol:fund.symbol,name:fund.name}]:[]});if(body.p_action==='add'){if(failSave){failSave=false;return send({message:'Temporary watchlist error'},503);}saved=true;return send({item:{investment_id:id}});}if(body.p_action==='remove'){saved=false;return send({removed:true});}}
 if(url.includes('/rpc/app_investment_fit'))return send(hasDna?{status:'available',fit:{match_score:82,recommendation_tier:'alternative',model_version:'suitability-v2.3',explanation:{fit_label:'Strong alternative',summary:'Based on your saved DNA.',watchouts:['Consider interest-rate risk.']}}}:{status:'no_dna'});
 if(url.includes('/rpc/get_current_investor_app_state'))return send({has_profile:true,dna:hasDna?{archetype:'MAVERICK',risk_tolerance:56,risk_capacity:64}:null,report:null,matches:hasDna?{top_matches:[],alternatives:[{symbol:'ZAG',name:fund.name,match_score:82,recommendation_tier:'alternative'}]}:null});
 throw Error('Unexpected request '+url);
});}
const ctx=await browser.newContext({viewport:{width:390,height:844}});await setup(ctx);const page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));const check=n=>console.log('PASS '+n);
await page.goto(origin+'/explore');await page.getByRole('link',{name:'View fund',exact:true}).click();await page.getByRole('heading',{name:'Could not load this fund'}).waitFor();failDetail=false;await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('heading',{name:fund.name,exact:true}).waitFor();check('View fund navigates correctly; detail errors stop loading and retry works');
assert.match(await page.locator('body').innerText(),/Income and broad bond exposure/);assert.match(await page.locator('body').innerText(),/0\.08%/);assert.match(await page.locator('body').innerText(),/Not available/);assert.match(await page.locator('body').innerText(),/100%/);check('profile, risks, allocation and string-valued MER render; absent price is not zero');
await page.getByRole('link',{name:'Create a free account',exact:true}).click();await page.getByRole('heading',{name:'Create your free account'}).waitFor();await page.getByLabel('Email address').fill('test@example.com');await page.getByRole('button',{name:'Create my free account'}).click();await page.getByRole('status').filter({hasText:'confirm your free account'}).waitFor();assert.ok(otp);check('optional registration requests account creation and preserves the fund in its email callback');
await page.evaluate(s=>localStorage.setItem('sb-dna-test-auth-token',JSON.stringify(s)),session);await page.reload();await page.getByRole('button',{name:'Save this fund to my watchlist',exact:true}).click();await page.getByRole('alert').filter({hasText:'Temporary watchlist error'}).waitFor();assert.equal(saved,false);await page.getByRole('button',{name:'Save this fund to my watchlist',exact:true}).click();await page.getByRole('status').filter({hasText:'ZAG is saved'}).waitFor();assert.ok(saved);check('failed save is visible; retry persists the selected fund without an arbitrary profile ID');
await page.getByRole('link',{name:'My watchlist',exact:true}).click();await page.waitForURL('**/watchlist');await page.getByRole('heading',{name:fund.name,exact:true}).waitFor();await page.reload();await page.getByRole('heading',{name:fund.name,exact:true}).waitFor();await page.getByRole('link',{name:'View fund',exact:true}).click();await page.getByText('Save your Investor DNA to see how this fund relates to your profile.').waitFor();check('saved fund survives reload and links back to details; missing DNA offers assessment');
hasDna=true;await page.reload();await page.getByText('Strong alternative',{exact:true}).waitFor();assert.match(await page.locator('body').innerText(),/82 \/ 100/);await page.screenshot({path:path.join(artifacts,'fund-connected-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('fund shows server DNA compatibility with no mobile overflow');
await page.goto(origin+'/profile');await page.getByRole('link',{name:'My DNA matches',exact:true}).click();await page.getByRole('link',{name:'View fund and DNA fit',exact:true}).click();await page.getByRole('heading',{name:fund.name,exact:true}).waitFor();check('profile matches lead to the correct fund details');
const other=await browser.newContext();await setup(other);await other.addInitScript(s=>localStorage.setItem('sb-dna-test-auth-token',JSON.stringify(s)),session);const second=await other.newPage();await second.goto(origin+'/watchlist');await second.getByRole('heading',{name:fund.name,exact:true}).waitFor();check('fresh browser with the same account reads the server watchlist');await other.close();
await page.goto(origin+'/watchlist');await page.getByRole('button',{name:'Remove',exact:true}).click();await page.getByRole('heading',{name:'Your watchlist is empty'}).waitFor();await page.reload();await page.getByRole('heading',{name:'Your watchlist is empty'}).waitFor();check('remove persists and renders a usable empty state');
await page.goto(origin+'/investment/00000000-0000-0000-0000-000000000002');await page.getByRole('heading',{name:'Fund not found'}).waitFor();check('unknown fund does not hang in loading');assert.deepEqual(errors,[]);check('no browser runtime errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
