"use client";
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {rpc} from '@/lib/supabase';
import {Fund,formatMetric} from '@/lib/investments';
import {useAccount} from '@/lib/use-account';
import type {AppState,MatchItem} from '@/lib/dna';

function fitLabel(m?:MatchItem){return m?.explanation?.fit_label||m?.fit_label||m?.recommendation_tier?.replaceAll('_',' ')||'Not matched'}
export default function Screener(){
 const {user,loading:authLoading}=useAccount();
 const [rows,setRows]=useState<Fund[]>([]),[q,setQ]=useState(''),[risk,setRisk]=useState(''),[sort,setSort]=useState('name'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [state,setState]=useState<AppState|null>(null),[dnaOnly,setDnaOnly]=useState(false),[selected,setSelected]=useState<string[]>([]);
 async function run(){setLoading(true);setError('');try{setRows(await rpc<Fund[]>('app_search_investments',{p_asset_type:'ETF',p_search:q||null,p_risk_level:risk||null,p_sort:sort==='dna_desc'?'name':sort,p_limit:100}))}catch(e){setError(e instanceof Error?e.message:'Could not load ETFs.')}finally{setLoading(false)}}
 useEffect(()=>{void run()},[]);
 useEffect(()=>{let active=true;setState(null);if(!user)return;rpc<AppState>('get_current_investor_app_state').then(x=>{if(active)setState(x)}).catch(()=>{});return()=>{active=false}},[user?.id]);
 const matches=useMemo(()=>new Map((state?.matches?.results||[]).map(m=>[m.symbol,m])),[state]);
 const displayed=useMemo(()=>{let out=[...rows];if(dnaOnly)out=out.filter(f=>matches.get(f.symbol)?.eligibility==='eligible');if(sort==='dna_desc')out.sort((a,b)=>(matches.get(b.symbol)?.match_score??-1)-(matches.get(a.symbol)?.match_score??-1));return out},[rows,dnaOnly,sort,matches]);
 const matchReady=!!state?.dna&&!!state?.matches;const matchStatus=state?.matches?.status;
 function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):current.length<3?[...current,id]:current)}
 return <section className="section"><div className="container"><div className="eyebrow">ETF Screener · DNA-powered</div><h1>Find ETFs, then see how they relate to you</h1><p className="muted">This screener intentionally remains ETF-only while Investor DNA expands its research universe to GICs, T-Bills, bonds and money-market structures. ETF facts come first; saved Investing DNA adds compatibility on top.</p>
 {matchReady?<div className="match-status-card ok"><strong>Your DNA is connected.</strong><p>{matchStatus==='available'?'Eligible ETF matches are identified using your current context.':matchStatus==='context_required'?'You are seeing DNA-only ETF compatibility until you add investment context.':matchStatus==='no_suitable_options'?'No ETF currently passes all fit limits; the screener still shows the research universe without forcing a recommendation.':'Your current match is under review, so rankings are not treated as eligible recommendations.'}</p></div>:!authLoading&&<div className="notice"><p>{user?'Complete or save your Investing DNA to add personal compatibility to the ETF screener.':'You can screen ETFs without an account. Sign in after completing Investing DNA to add your personal fit layer.'}</p></div>}
 <form className="dna-toolbar" onSubmit={e=>{e.preventDefault();void run()}}><label>Search<input className="field" placeholder="Symbol or name" value={q} onChange={e=>setQ(e.target.value)}/></label><label>Official risk<select className="field" value={risk} onChange={e=>setRisk(e.target.value)}><option value="">All risk levels</option><option>Low</option><option>Low to Medium</option><option>Medium</option><option>Medium to High</option><option>High</option></select></label><label>Sort<select className="field" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="return_1y_desc">1-year return</option><option value="mer_asc">Lowest MER</option><option value="aum_desc">Largest AUM</option>{matchReady&&<option value="dna_desc">Closest DNA fit</option>}</select></label><button className="btn primary" disabled={loading}>Apply</button>{matchReady&&matchStatus==='available'&&<label><span>DNA filter</span><button type="button" className="btn" aria-pressed={dnaOnly} onClick={()=>setDnaOnly(x=>!x)}>{dnaOnly?'Showing eligible only':'Show eligible only'}</button></label>}</form>
 <div className="screener-summary"><p className="muted">{loading?'Loading…':`${displayed.length} ETF${displayed.length===1?'':'s'} shown`}</p><p className="fine muted">Select up to 3 ETFs to compare side by side. Use Explore for cross-asset research.</p></div>
 {error&&<p className="notice" role="alert">{error}</p>}{loading?<p>Loading ETFs…</p>:!displayed.length&&!error?<p>No ETFs match these filters.</p>:<table className="table"><thead><tr><th>Compare</th><th>ETF</th><th>Official risk</th><th>DNA fit</th><th>1-year return</th><th>MER</th><th>Details</th></tr></thead><tbody>{displayed.map(x=>{const m=matches.get(x.symbol);return <tr key={x.id}><td><input aria-label={`Select ${x.symbol} for comparison`} type="checkbox" checked={selected.includes(x.id)} disabled={!selected.includes(x.id)&&selected.length>=3} onChange={()=>toggle(x.id)}/></td><td><b>{x.symbol}</b> · {x.name}</td><td>{x.risk_level||'Not available'}</td><td>{m?<div className="dna-fit-cell"><strong>{m.match_score==null?'Review':`${Math.round(m.match_score)}/100`}</strong><small>{fitLabel(m)}</small></div>:<span className="muted">{matchReady?'Not ranked':'Add DNA'}</span>}</td><td>{formatMetric(x.return_1y_pct,'%')}</td><td>{formatMetric(x.mer_pct,'%')}</td><td><Link className="btn" href={'/investment/'+x.id}>View ETF</Link></td></tr>})}</tbody></table>}
 {selected.length>0&&<div className="selection-bar"><span>{selected.length} selected · choose up to 3</span><div className="actions" style={{margin:0}}>{selected.length>=2&&<Link className="btn primary" href={`/compare?ids=${selected.join(',')}`}>Compare selected</Link>}<button className="btn" onClick={()=>setSelected([])}>Clear</button></div></div>}
 </div></section>;
}
