import Link from 'next/link';
import {PORTFOLIO_BLUEPRINT_VERSION} from '@/lib/portfolio-blueprint';

export default function PortfolioBlueprintMethodology(){return <section className="section"><div className="container narrow">
  <div className="eyebrow">Portfolio Blueprint methodology</div>
  <h1>How the three asset-class scenarios are built</h1>
  <div className="card"><h2>Purpose</h2><p>Portfolio Blueprint translates a completed Investor DNA plus one complete investment-goal context into three educational asset-class scenarios: More Defensive, Your Core Blueprint and More Growth.</p><p>It does not choose a security, geographic market, sector, manager or fund. The current output is limited to Equity, Fixed income and Cash.</p></div>
  <div className="card"><h2>Inputs</h2><p>The current model uses risk tolerance, financial capacity, time horizon, liquidity need, goal type and the stated need for principal protection. It does not generate a blueprint when either risk score or any required goal-context field is unavailable.</p></div>
  <div className="card"><h2>Guardrails before growth</h2><p>Financial capacity acts as a ceiling rather than a bonus: a high willingness to take risk cannot override a lower ability to absorb loss. Time horizon, liquidity, goal type and principal-protection needs can reduce market exposure further.</p><p>A full-principal-protection requirement, an emergency-reserve goal or a horizon under one year prevents the More Growth scenario from increasing equity beyond the Core Blueprint. The interface shows that constraint instead of inventing a more aggressive allocation.</p></div>
  <div className="card"><h2>What changes between scenarios</h2><p>The Core Blueprint is the centre produced by the current inputs. The More Defensive scenario reduces equity and increases the stability/liquidity buffer. The More Growth scenario can increase equity only when the same goal constraints leave room to do so.</p><p>All displayed allocations use five-percentage-point increments to avoid implying a level of precision the research model does not support.</p></div>
  <div className="card"><h2>Research status</h2><p>Current model version: <strong>{PORTFOLIO_BLUEPRINT_VERSION}</strong>.</p><p>This is a deterministic research rule set, not an empirically validated portfolio optimizer and not a forecast of expected return. The allocation logic should be reviewed during the pilot and before any positioning as personalized investment advice.</p></div>
  <div className="actions"><Link className="btn" href="/research">Research & limitations</Link><Link className="btn primary" href="/dna/result">Back to my report</Link></div>
</div></section>}
