import Link from 'next/link';

export default function PilotPrivacy(){return <section className="section"><div className="container narrow">
  <div className="eyebrow">Pilot privacy summary</div><h1>What the pilot records</h1>
  <div className="card"><h2>Product analytics</h2><p>During the pilot, Investor DNA records privacy-minimized product events so we can understand where people complete, stop, explore, save and return.</p><p>The analytics layer uses a random browser visitor ID and a random browser-session ID. It may also record the route, event type, an investment identifier when relevant, and limited product-state metadata.</p><p>The analytics event tables are not designed to store your name, email address, IP address or the text of your questionnaire answers.</p></div>
  <div className="card"><h2>Assessment and account data</h2><p>Your Investing DNA assessment answers are stored by the assessment service because they are required to calculate and reproduce your profile. If you choose to create an account and save your result, Investor DNA can associate your completed assessment, investment context and saved investments with that account.</p><p>A completed guest assessment keeps only a limited claim ticket in browser storage for optional account saving; the full completed guest draft is not kept there after completion.</p></div>
  <div className="card"><h2>Investment research activity</h2><p>The pilot can record that an investment research page, Compare, Screener or Watchlist was used and can attach an internal investment identifier to that product event. It does not turn your research activity into an order or execute a trade.</p></div>
  <div className="card"><h2>Pilot feedback</h2><p>If you submit pilot feedback, we record your ease, trust and usefulness scores, whether the Match explanation was understood, whether you would return, and any optional text you choose to provide. Feedback is used to improve the research-stage product.</p></div>
  <div className="card"><h2>Controlled cognitive study</h2><p>The cognitive-study route is separate from normal development traffic. Participants enter through a moderator-controlled invite code so the research cohort is not silently mixed with ordinary testing.</p><p>This page is a transparent pilot summary, not the final legal privacy policy for a public launch. Formal privacy and legal review remain pre-launch gates.</p></div>
  <div className="actions"><Link className="btn" href="/research">Research & limitations</Link><Link className="btn primary" href="/feedback">Pilot feedback</Link></div>
</div></section>}
