"use client";

import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import Link from 'next/link';
import {supabase,rpc,pilot} from '@/lib/supabase';
import {clearDraft,hasCompleteInvestmentContext,normalizePersonalization,readClaimTicket,readDraft} from '@/lib/dna';
import type {AppState,ClaimTicket,MatchItem,PersonalizationProfile} from '@/lib/dna';
import {displayArchetype} from '@/lib/dna-presentation';
import {useAccount} from '@/lib/use-account';
import {validId} from '@/lib/investments';
import {getInstrument,instrumentWatchlist,saveInstrument} from '@/lib/instruments';
import {trackProductEvent} from '@/lib/analytics';
import {clearReturningWorkspaceCache} from '@/lib/returning-workspace';
import {useLocale} from '@/lib/locale';
import type {Instrument,SavedInstrument} from '@/lib/instruments';

export default function Profile(){
 const {user,loading:authLoading}=useAccount();
 const [state,setState]=useState<AppState|null>(null);
 const [pending,setPending]=useState<ClaimTicket|null>(null);
 const [items,setItems]=useState<SavedInstrument[]>([]);
 const [intent,setIntent]=useState<Instrument|null>(null);
 const [intentId,setIntentId]=useState<string|null>(null);
 const [loading,setLoading]=useState(true);
 const [busy,setBusy]=useState(false);
 const [email,setEmail]=useState('');
 const [sentTo,setSentTo]=useState('');
 const [cooldown,setCooldown]=useState(0);
 const [message,setMessage]=useState('');
 const [error,setError]=useState('');
 const [listError,setListError]=useState('');
 const [retry,setRetry]=useState(0);
 const [autoSave,setAutoSave]=useState(false);
 const [listLoaded,setListLoaded]=useState(false);
 const [callbackMode,setCallbackMode]=useState<string|null>(null);
 const restoredTracked=useRef(false);
 const {locale,pick}=useLocale();

 useEffect(()=>{const url=new URL(location.href);setAutoSave(url.searchParams.get('save')==='dna');const fragment=new URLSearchParams(location.hash.slice(1));const authError=fragment.get('error_description')||url.searchParams.get('error_description');if(authError){setError(friendlyAuthError(authError,locale));const clean=new URL(location.href);clean.searchParams.delete('error');clean.searchParams.delete('error_code');clean.searchParams.delete('error_description');clean.hash='';history.replaceState(history.state,'',clean.pathname+clean.search)}const id=url.searchParams.get('investment');if(!validId(id))return;setIntentId(id);let active=true;getInstrument(id).then(data=>{if(active)setIntent(data)}).catch(()=>{if(active)setError(pick('Could not load the investment you wanted to save.','Impossible de charger le placement que vous vouliez enregistrer.'))});return()=>{active=false}},[]);
 useEffect(()=>{if(!user||!location.hash)return;const fragment=new URLSearchParams(location.hash.slice(1));const authKeys=['access_token','refresh_token','expires_in','expires_at','token_type','type','error','error_code','error_description'];if(!authKeys.some(key=>fragment.has(key)))return;const url=new URL(location.href);const mode=url.searchParams.get('save')==='dna'?'dna_claim':validId(url.searchParams.get('investment'))?'investment_intent':'profile';setCallbackMode(mode);restoredTracked.current=false;void trackProductEvent('auth_callback_session_established',{metadata:{source:'magic_link_callback',mode}});history.replaceState(history.state,'',url.pathname+url.search)},[user?.id]);
 useEffect(()=>{if(cooldown<=0)return;const timer=window.setInterval(()=>setCooldown(v=>Math.max(0,v-1)),1000);return()=>window.clearInterval(timer)},[cooldown]);
 useEffect(()=>{let active=true;setState(null);setItems([]);setListLoaded(false);setListError('');setLoading(true);const draft=readDraft(user?.id||null);const claim=readClaimTicket()||(draft?.result&&!draft.result.account_linked?{version:1 as const,createdAt:draft.createdAt,session:draft.session,personalization:draft.personalization}:null);setPending(claim);if(authLoading)return;if(!user){setLoading(false);setListLoaded(true);return}rpc<AppState>('get_current_investor_app_state').then(data=>{if(active)setState(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});instrumentWatchlist().then(data=>{if(active)setItems(data.items)}).catch(e=>{if(active)setListError(e.message)}).finally(()=>{if(active)setListLoaded(true)});return()=>{active=false}},[user?.id,authLoading,retry]);
 useEffect(()=>{if(autoSave&&user&&pending&&!busy){setAutoSave(false);void claimAssessment()}},[autoSave,user?.id,pending?.session.assessment_id]);
 useEffect(()=>{if(!user||!callbackMode||loading||!listLoaded||!state||listError||restoredTracked.current)return;restoredTracked.current=true;const context=state.report?.investment_context||state.dna?.investment_context||null;void trackProductEvent('account_state_restored',{metadata:{source:'magic_link_callback',mode:callbackMode,has_dna:!!state.dna,has_context:hasCompleteInvestmentContext(context),watchlist_count:items.length}})},[user?.id,callbackMode,loading,listLoaded,state?.assessment_id,items.length,listError]);


 async function requestMagicLink(){if(!supabase||busy||cooldown>0)return;const address=email.trim();if(!address)return;setBusy(true);setError('');setMessage('');try{const redirect=new URL('/profile',location.origin);if(intentId)redirect.searchParams.set('investment',intentId);if(pending)redirect.searchParams.set('save','dna');const {error:authError}=await supabase.auth.signInWithOtp({email:address,options:{shouldCreateUser:true,emailRedirectTo:redirect.toString(),data:pending?.personalization||undefined}});if(authError)throw authError;setSentTo(address);setCooldown(60);setMessage(pick('Use the newest email link only. Keep this tab open while you check your inbox.','Utilisez uniquement le lien le plus récent. Gardez cet onglet ouvert pendant que vous consultez votre courriel.'));void trackProductEvent('secure_link_requested',{metadata:{source:intentId?'investment_intent':pending?'dna_claim':'profile'}})}catch(e){const raw=e instanceof Error?e.message:pick('Unable to send an email link.','Impossible d’envoyer le lien par courriel.');setError(friendlyAuthError(raw,locale));if(/rate limit|too many/i.test(raw))setCooldown(60)}finally{setBusy(false)}}
 async function sendMagicLink(event:FormEvent){event.preventDefault();await requestMagicLink()}
 function changeEmail(){setSentTo('');setMessage('');setError('')}
 async function claimAssessment(){if(!pending||!user||busy)return;setBusy(true);setError('');setMessage('');try{if(pending.personalization&&supabase){const {error:metaError}=await supabase.auth.updateUser({data:pending.personalization});if(metaError)throw metaError}const result=await pilot<{claimed:boolean}>('claim_assessment',pending.session);if(!result.claimed)throw new Error(pick('The service has not confirmed saving your DNA.','Le service n’a pas confirmé l’enregistrement de votre DNA.'));clearDraft();setPending(null);setMessage(pick('Your Investor DNA is saved to your dashboard.','Votre Investor DNA est enregistré dans votre tableau de bord.'));setRetry(v=>v+1)}catch(e){setError(e instanceof Error?e.message:pick('Unable to save this DNA right now.','Impossible d’enregistrer ce DNA pour le moment.'))}finally{setBusy(false)}}
 async function saveIncomingInvestment(){if(!intent||!user||busy)return;setBusy(true);setError('');try{const result=await saveInstrument(intent.id);if(!result.item)throw new Error(pick('Saving was not confirmed.','L’enregistrement n’a pas été confirmé.'));setMessage(locale==='fr'?`${intent.symbol||intent.name} est enregistré dans votre liste de suivi.`:`${intent.symbol||intent.name} is saved to your watchlist.`);void trackProductEvent('watchlist_saved',{investment_id:intent.id,metadata:{source:'profile_intent'}});setRetry(v=>v+1)}catch(e){setError(e instanceof Error?e.message:pick('Unable to save this investment.','Impossible d’enregistrer ce placement.'))}finally{setBusy(false)}}
 async function signOut(){if(!supabase||busy)return;setBusy(true);try{const currentUserId=user?.id;const {error:authError}=await supabase.auth.signOut({scope:'local'});if(authError)throw authError;clearReturningWorkspaceCache(currentUserId);clearDraft();restoredTracked.current=false;setCallbackMode(null);setPending(null);setState(null);setItems([]);setMessage(pick('You have signed out.','Vous êtes déconnecté.'))}catch(e){setError(e instanceof Error?e.message:pick('Unable to sign out.','Impossible de se déconnecter.'))}finally{setBusy(false)}}

 const intentSaved=items.some(item=>item.investment_id===intent?.id);
 const closest:MatchItem|undefined=state?.matches?.top_matches?.[0]||state?.matches?.alternatives?.[0]||state?.matches?.results?.find(item=>item.eligibility==='eligible')||state?.matches?.results?.[0];
 const personal=normalizePersonalization(user?.user_metadata)||personalFromState(state);
 return <section className={user?'profile-page dashboard-page':'profile-page'}><div className={user?'container dashboard-container':'container narrow'}>{error&&<div className="notice dashboard-alert" role="alert"><p>{error}</p>{user&&<button className="btn" onClick={()=>{setError('');setRetry(v=>v+1)}}>{pick("Retry","Réessayer")}</button>}</div>}{authLoading||loading?<div className="card"><p role="status">{pick("Loading your Investor DNA…","Chargement de votre Investor DNA…")}</p></div>:user?<SignedInDashboard email={user.email||''} personal={personal} intent={intent} intentSaved={intentSaved} pending={pending} state={state} items={items} listError={listError} closest={closest} busy={busy} onSaveIntent={()=>void saveIncomingInvestment()} onClaim={()=>void claimAssessment()} onRetryList={()=>setRetry(v=>v+1)} onSignOut={()=>void signOut()}/>:<SignedOutCard email={email} sentTo={sentTo} cooldown={cooldown} busy={busy} message={message} pending={pending} onEmail={setEmail} onSubmit={sendMagicLink} onResend={()=>void requestMagicLink()} onChangeEmail={changeEmail}/>} {user&&message&&<p className="notice dashboard-message" role="status">{message}</p>}</div></section>;
}

function SignedInDashboard({email,personal,intent,intentSaved,pending,state,items,listError,closest,busy,onSaveIntent,onClaim,onRetryList,onSignOut}:{email:string;personal:PersonalizationProfile|null;intent:Instrument|null;intentSaved:boolean;pending:ClaimTicket|null;state:AppState|null;items:SavedInstrument[];listError:string;closest?:MatchItem;busy:boolean;onSaveIntent:()=>void;onClaim:()=>void;onRetryList:()=>void;onSignOut:()=>void}){
 const {locale,pick}=useLocale();
 const dna=state?.dna;const context=state?.report?.investment_context||dna?.investment_context;const contextComplete=hasCompleteInvestmentContext(context);const archetype=dna?.archetype?displayArchetype(dna.archetype):'Investor DNA';const matchStatus=state?.matches?.status;const numericMatch=matchStatus==='available'&&closest?.match_score!=null;const firstName=personal?.first_name;
 return <><MobileDashboardHome personal={personal} state={state} items={items} closest={closest} intent={intent} intentSaved={intentSaved} busy={busy} onSaveIntent={onSaveIntent}/><div className="dashboard-reference-shell"><aside className="dashboard-reference-rail" aria-label={pick("Dashboard navigation","Navigation du tableau de bord")}><span className="rail-title">{pick("My workspace","Mon espace")}</span><Link className="active" href="/profile">⌂ {pick("Dashboard","Tableau de bord")}</Link><Link href="/dna/result">⌬ {pick("My DNA","Mon DNA")}</Link><Link href="/dna/context?returnTo=/profile">◎ {pick("My goal","Mon objectif")}</Link><Link href="/watchlist">♡ {pick("Watchlist","Liste de suivi")}</Link><Link href="/compare">⇄ {pick("Compare","Comparer")}</Link></aside><div className="dashboard-reference-main"><header className="dashboard-hero"><div><div className="eyebrow">My Investor DNA</div><h1>{firstName?(locale==='fr'?`Bon retour, ${firstName}`:`Welcome back, ${firstName}`):pick('Your research workspace','Votre espace de recherche')}</h1><p>{pick("Same discipline. A brighter tomorrow. Your DNA stays steady while goals and research evolve around it.","La même discipline, pour un avenir plus clair. Votre DNA reste stable tandis que vos objectifs et votre recherche évoluent.")}</p></div><div className="dashboard-account"><span>{pick("Signed in as","Connecté comme")}</span><strong>{email}</strong><button className="dashboard-signout" disabled={busy} onClick={onSignOut}>{pick("Sign out","Se déconnecter")}</button></div></header>
 {intent&&<div className="dashboard-intent"><div><span className="dashboard-kicker">{pick("Save intent","Placement à enregistrer")}</span><strong>{intent.symbol||intent.name}</strong><p>{intentSaved?pick('Already in your watchlist.','Déjà dans votre liste de suivi.'):pick('Your research intent is still intact.','Votre recherche est toujours prête à être reprise.')}</p></div><div className="actions compact">{!intentSaved&&<button className="btn primary" disabled={busy} onClick={onSaveIntent}>{pick("Save to watchlist","Enregistrer dans la liste")}</button>}<Link className="btn" href={'/investment/'+intent.id}>{pick("View details","Voir les détails")}</Link></div></div>}
 {pending&&<div className="dashboard-intent dashboard-claim"><div><span className="dashboard-kicker">{pick("DNA ready","DNA prêt")}</span><strong>{pick("Save your completed report","Enregistrer votre rapport terminé")}</strong><p>{pick("Attach this assessment to your account so it remains available in your dashboard.","Associez cette évaluation à votre compte afin qu’elle reste disponible dans votre tableau de bord.")}</p></div><button className="btn primary" disabled={busy} onClick={onClaim}>{busy?pick('Saving…','Enregistrement…'):pick('Save my DNA','Enregistrer mon DNA')}</button></div>}
 <div className="dashboard-grid"><section className="dashboard-card dashboard-dna"><div className="dashboard-card-head"><div><span className="dashboard-kicker">My Investor DNA</span><h2>{dna?archetype:pick('Not connected yet','Pas encore connecté')}</h2></div><span className={dna?'status-dot complete':'status-dot'}>{dna?pick('Saved','Enregistré'):pick('Start','Commencer')}</span></div>{dna?<><p>{personal?.age?`Age ${personal.age} · `:''}{pick("Your personal research profile is saved and does not change just because you add a different investment goal.","Votre profil de recherche personnel est enregistré et ne change pas simplement parce que vous ajoutez un autre objectif de placement.")}</p><div className="dashboard-stats"><div><span>{pick("Risk tolerance","Tolérance au risque")}</span><strong>{formatScore(dna.risk_tolerance)}</strong></div><div><span>{pick("Risk capacity","Capacité de risque")}</span><strong>{formatScore(dna.risk_capacity)}</strong></div></div><div className="dashboard-card-actions"><Link className="btn primary" href="/dna/result">{pick("View full report","Voir le rapport complet")}</Link><Link className="text-link" href="/dna/assessment?fresh=1">{pick("Retake assessment →","Refaire l’évaluation →")}</Link></div></>:<><p>{pick("Complete the assessment to create your personal Investor DNA report.","Terminez l’évaluation pour créer votre rapport Investor DNA personnel.")}</p><Link className="btn primary" href="/dna/assessment">{pick("Start Investing DNA","Commencer Investing DNA")}</Link></>}</section>
 <section className="dashboard-card dashboard-context"><div className="dashboard-card-head"><div><span className="dashboard-kicker">{pick("Current investment goal","Objectif de placement actuel")}</span><h2>{contextComplete?contextLabel(context?.goal,locale):pick('Put your DNA into action','Mettre votre DNA en action')}</h2></div><span className={contextComplete?'status-dot complete':'status-dot'}>{contextComplete?pick('Connected','Connecté'):pick('Add goal','Ajouter un objectif')}</span></div>{contextComplete?<><p>{horizonLabel(context?.time_horizon,locale)}{context?.amount_to_invest!=null?` · CAD ${Number(context.amount_to_invest).toLocaleString()}`:''}</p><div className="context-chips">{context?.liquidity_need&&<span>{context.liquidity_need.replaceAll('_',' ')} liquidity</span>}</div><div className="dashboard-card-actions"><Link className="btn" href="/dna/context?returnTo=/profile">{pick("Edit goal","Modifier l’objectif")}</Link><Link className="text-link" href="/dna/result">{pick("View applied report →","Voir le rapport contextualisé →")}</Link></div></>:<><p>{pick("Add a goal, horizon, access need and principal-protection choice. Your name, age and personal DNA stay with the report.","Ajoutez un objectif, un horizon, un besoin d’accès aux fonds et un choix de protection du capital. Votre nom, votre âge et votre DNA personnel restent associés au rapport.")}</p><Link className="btn primary" href="/dna/context?returnTo=/profile">{pick("Add investment goal","Ajouter un objectif de placement")}</Link></>}</section>
 <section className="dashboard-card dashboard-match"><div className="dashboard-card-head"><div><span className="dashboard-kicker">DNA Match</span><h2>{numericMatch?`${closest?.symbol} · ${Math.round(closest!.match_score!)}/100`:matchStatus==='context_required'?pick('Goal context needed','Contexte de l’objectif requis'):matchStatus==='review_required'?pick('Review required','Révision requise'):dna?pick('Compatibility workspace','Espace de compatibilité'):pick('Connect DNA first','Connectez d’abord votre DNA')}</h2></div></div><MatchDashboardCopy matchStatus={matchStatus} closest={closest} hasDna={!!dna}/></section>
 <section className="dashboard-card dashboard-watchlist"><div className="dashboard-card-head"><div><span className="dashboard-kicker">{pick("Saved research","Recherche enregistrée")}</span><h2>{locale==='fr'?`${items.length} placement${items.length===1?'':'s'} enregistré${items.length===1?'':'s'}`:`${items.length} saved investment${items.length===1?'':'s'}`}</h2></div><Link className="text-link" href="/watchlist">{pick("View all →","Voir tout →")}</Link></div><SavedInvestments items={items} listError={listError} onRetry={onRetryList}/></section></div>
 <section className="dashboard-continue"><div><span className="dashboard-kicker">{pick("Your journey continues","Votre parcours continue")}</span><h2>{pick("Explore more opportunities.","Explorez davantage de possibilités.")}</h2><p>{pick("Explore investments, compare options and build your watchlist around the research that matters to you.","Explorez des placements, comparez les options et construisez votre liste de suivi autour de la recherche qui compte pour vous.")}</p></div><div className="dashboard-quick-links"><Link href="/explore">Explore <span>Cross-asset research</span></Link><Link href="/screener">ETF Screener <span>Filter the ETF universe</span></Link><Link href="/compare">Compare <span>Side-by-side research</span></Link><Link href="/match">DNA Match <span>Compatibility, not a recommendation</span></Link></div></section></div></div></>;
}

function MobileDashboardHome({personal,state,items,closest,intent,intentSaved,busy,onSaveIntent}:{personal:PersonalizationProfile|null;state:AppState|null;items:SavedInstrument[];closest?:MatchItem;intent:Instrument|null;intentSaved:boolean;busy:boolean;onSaveIntent:()=>void}){
 const {locale,pick}=useLocale();
 const dna=state?.dna;
 const context=state?.report?.investment_context||dna?.investment_context;
 const contextComplete=hasCompleteInvestmentContext(context);
 const archetype=dna?.archetype?displayArchetype(dna.archetype):pick('Your Investor DNA','Votre Investor DNA');
 const matchAvailable=state?.matches?.status==='available'&&closest?.match_score!=null;
 const firstName=personal?.first_name;
 return <div className="mobile-dashboard-home">
  <header className="mobile-home-greeting">
   <div className="eyebrow">Investing DNA</div>
   <h1>{firstName?(locale==='fr'?`Ravi de vous revoir, ${firstName}`:`Good to see you, ${firstName}`):pick('Your investing workspace','Votre espace de placement')}</h1>
   <p>{pick("Know yourself. Research with context.","Mieux vous connaître. Rechercher avec contexte.")}</p>
  </header>

  {intent&&<section className="mobile-home-intent">
   <div>
    <span className="mobile-card-kicker">{pick("Save research","Enregistrer la recherche")}</span>
    <strong>{intent.symbol||intent.name}</strong>
    <small>{intentSaved?pick('Already saved to your watchlist.','Déjà enregistré dans votre liste de suivi.'):pick('Keep this research connected to your account.','Associez cette recherche à votre compte.')}</small>
   </div>
   <div className="mobile-home-intent-actions">
    {!intentSaved&&<button className="btn primary" disabled={busy} onClick={onSaveIntent}>{busy?pick('Saving…','Enregistrement…'):pick('Save to watchlist','Enregistrer dans la liste')}</button>}
    <Link className="btn" href={'/investment/'+intent.id}>View details</Link>
   </div>
  </section>}

  <Link className="mobile-dna-summary" href={dna?'/dna/result':'/dna/assessment'}>
   <div className="mobile-dna-summary-copy">
    <span className="mobile-card-kicker">{pick("Your Investor DNA","Votre Investor DNA")}</span>
    <h2>{dna?archetype:pick('Build your profile','Créer votre profil')}</h2>
    <p>{dna?pick('Your personal risk and decision profile is ready to use across the platform.','Votre profil personnel de risque et de décision est prêt à être utilisé dans la plateforme.'):pick('Complete 28 questions to create your personal Investor DNA.','Répondez à 28 questions pour créer votre Investor DNA personnel.')}</p>
   </div>
   <div className="mobile-dna-orbit" aria-hidden="true"><span>{dna?formatScore(dna.risk_tolerance).replace('/100',''):'DNA'}</span><small>{dna?'risk':'start'}</small></div>
   <span className="mobile-card-arrow" aria-hidden="true">→</span>
  </Link>

  <div className="mobile-home-snapshot">
   <Link href={contextComplete?'/dna/context?returnTo=/profile':'/dna/context?returnTo=/profile'}>
    <span>{pick("Current goal","Objectif actuel")}</span>
    <strong>{contextComplete?contextLabel(context?.goal,locale):pick('Add context','Ajouter le contexte')}</strong>
    <small>{contextComplete?horizonLabel(context?.time_horizon,locale):pick('Goal · horizon · access need','Objectif · horizon · besoin d’accès')}</small>
   </Link>
   <Link href="/match">
    <span>DNA Match</span>
    <strong>{matchAvailable?`${Math.round(closest!.match_score!)}%`:state?.matches?.status==='review_required'?pick('Review','Réviser'):pick('Open','Ouvrir')}</strong>
    <small>{matchAvailable?(closest?.symbol||closest?.name||pick('Closest fit','Compatibilité la plus proche')):pick('Compatibility research','Recherche de compatibilité')}</small>
   </Link>
  </div>

  <section className="mobile-home-section">
   <div className="mobile-home-section-head"><div><span className="mobile-card-kicker">{pick("Quick actions","Actions rapides")}</span><h2>{pick("Pick up where you left off","Reprendre là où vous vous êtes arrêté")}</h2></div></div>
   <div className="mobile-action-list">
    <Link href={dna?'/dna/result':'/dna/assessment'}><span className="mobile-action-icon">⌁</span><span><strong>{dna?pick('View my DNA','Voir mon DNA'):pick('Start my DNA','Commencer mon DNA')}</strong><small>{dna?pick('Your report and key signals','Votre rapport et vos signaux clés'):pick('28 focused questions','28 questions ciblées')}</small></span><b>›</b></Link>
    <Link href="/explore"><span className="mobile-action-icon">⌕</span><span><strong>{pick("Explore investments","Explorer les placements")}</strong><small>{pick("ETFs, GICs, T-Bills and bonds","FNB, CPG, bons du Trésor et obligations")}</small></span><b>›</b></Link>
    <Link href="/watchlist"><span className="mobile-action-icon">♡</span><span><strong>{pick("Saved research","Recherche enregistrée")}</strong><small>{items.length?(locale==='fr'?`${items.length} placement${items.length===1?'':'s'} enregistré${items.length===1?'':'s'}`:`${items.length} saved investment${items.length===1?'':'s'}`):pick('Nothing saved yet','Aucun placement enregistré')}</small></span><b>›</b></Link>
   </div>
  </section>

  {items.length>0&&<section className="mobile-home-section mobile-saved-preview">
   <div className="mobile-home-section-head"><div><span className="mobile-card-kicker">{pick("Watchlist","Liste de suivi")}</span><h2>{pick("Saved for later","Enregistrés pour plus tard")}</h2></div><Link href="/watchlist">{pick("View all","Voir tout")}</Link></div>
   <div className="mobile-saved-list">{items.slice(0,3).map(item=><Link key={item.investment_id} href={'/investment/'+item.investment_id}><span className="mobile-saved-symbol">{item.symbol||'Fund'}</span><span><strong>{item.name}</strong><small>{pick("Saved research","Recherche enregistrée")}</small></span><b>›</b></Link>)}</div>
  </section>}
 </div>;
}

function MatchDashboardCopy({matchStatus,closest,hasDna}:{matchStatus?:string;closest?:MatchItem;hasDna:boolean}){const {pick}=useLocale();if(!hasDna)return <><p>{pick("Complete Investor DNA before using personal ETF compatibility.","Terminez Investor DNA avant d’utiliser la compatibilité personnalisée des FNB.")}</p><Link className="btn primary" href="/dna/assessment">{pick("Start assessment","Commencer l’évaluation")}</Link></>;if(matchStatus==='available'&&closest)return <><p>{closest.name||closest.symbol} {pick("is currently the closest research compatibility in your eligible ETF set. This is not a recommendation.","est actuellement la compatibilité de recherche la plus proche parmi vos FNB admissibles. Ce n’est pas une recommandation.")}</p><Link className="btn primary" href="/match">{pick("Open DNA Match","Ouvrir DNA Match")}</Link></>;if(matchStatus==='context_required')return <><p>{pick("Numeric scores stay hidden until this money has a goal, horizon, access need and principal-protection choice.","Les scores numériques restent masqués tant que cet argent n’a pas d’objectif, d’horizon, de besoin d’accès et de choix de protection du capital.")}</p><Link className="btn primary" href="/dna/context?returnTo=/profile">{pick("Add goal context","Ajouter le contexte de l’objectif")}</Link></>;if(matchStatus==='review_required')return <><p>{pick("A safety or data-review gate is active, so ranked numeric results are paused.","Une vérification de sécurité ou de données est active; les résultats numériques classés sont donc suspendus.")}</p><Link className="btn primary" href="/match">{pick("Review Match status","Réviser l’état du Match")}</Link></>;return <><p>{pick("Your DNA is connected. Open Match to continue compatibility research.","Votre DNA est connecté. Ouvrez Match pour poursuivre la recherche de compatibilité.")}</p><Link className="btn primary" href="/match">Open DNA Match</Link></>}
function SavedInvestments({items,listError,onRetry}:{items:SavedInstrument[];listError:string;onRetry:()=>void}){const {pick}=useLocale();if(listError)return <div className="dashboard-inline-error"><p>{listError}</p><button className="btn" onClick={onRetry}>{pick("Retry watchlist","Réessayer la liste de suivi")}</button></div>;if(!items.length)return <><p>{pick("No saved investments yet. Save from any investment page and it will stay here.","Aucun placement enregistré pour le moment. Enregistrez-en un depuis n’importe quelle fiche pour le retrouver ici.")}</p><Link className="btn" href="/explore">{pick("Explore investments","Explorer les placements")}</Link></>;return <div className="dashboard-saved-list">{items.slice(0,3).map(item=><Link key={item.investment_id} href={'/investment/'+item.investment_id}><strong>{item.symbol||item.name}</strong><span>{item.name}</span></Link>)}</div>}
function SignedOutCard({email,sentTo,cooldown,busy,message,pending,onEmail,onSubmit,onResend,onChangeEmail}:{email:string;sentTo:string;cooldown:number;busy:boolean;message:string;pending:ClaimTicket|null;onEmail:(value:string)=>void;onSubmit:(event:FormEvent)=>void;onResend:()=>void;onChangeEmail:()=>void}){const {pick}=useLocale();return <div className="card auth-card"><div className="eyebrow">My Investor DNA</div><h1>{pending?pick('Save your Investor DNA','Enregistrer votre Investor DNA'):pick('Create your free account or sign in','Créer votre compte gratuit ou vous connecter')}</h1>{sentTo?<div className="auth-sent"><h2>{pick("Check your email","Consultez votre courriel")}</h2><p>{pick("We sent a secure sign-in link to","Nous avons envoyé un lien de connexion sécurisé à")} <strong>{sentTo}</strong>.</p><div className="auth-browser-note"><strong>{pick("Keep this tab open.","Gardez cet onglet ouvert.")}</strong><p>{pick("Open the newest sign-in link on this same device and browser. If your mail app opens it somewhere else, copy the link and paste it into this browser.","Ouvrez le lien de connexion le plus récent sur ce même appareil et dans ce même navigateur. Si votre application de courriel l’ouvre ailleurs, copiez le lien et collez-le dans ce navigateur.")}</p></div><div className="auth-sent-actions"><button type="button" className="btn primary" disabled={busy||cooldown>0} onClick={onResend}>{busy?pick('Sending…','Envoi…'):cooldown>0?(pick('Send again in','Renvoyer dans')+` ${cooldown}s`):pick('Send a new link','Envoyer un nouveau lien')}</button><button type="button" className="btn" disabled={busy} onClick={onChangeEmail}>{pick("Use a different email","Utiliser une autre adresse")}</button></div></div>:<form onSubmit={onSubmit}><p>{pending?pick('Use your email to attach the completed report to your dashboard.','Utilisez votre courriel pour associer le rapport terminé à votre tableau de bord.'):pick('Use a secure email link — no password required.','Utilisez un lien de connexion sécurisé — aucun mot de passe requis.')}</p><label className="context-field"><span>{pick("Email address","Adresse courriel")}</span><input type="email" autoComplete="email" required value={email} onChange={e=>onEmail(e.target.value)} placeholder="you@example.com"/></label><button className="btn primary" disabled={busy||cooldown>0}>{busy?pick('Sending…','Envoi…'):cooldown>0?(pick('Try again in','Réessayer dans')+` ${cooldown}s`):pick('Email me a secure link','M’envoyer un lien sécurisé')}</button></form>}{message&&<p className="notice" role="status">{message}</p>}</div>}
function formatScore(value?:number){return typeof value==='number'?`${Math.round(value)}/100`:'—'}
function contextLabel(value:string|null|undefined,locale:"en"|"fr"="en"){const en:Record<string,string>={growth:'Long-term growth',retirement:'Retirement',house_purchase:'Home purchase',major_purchase:'Major purchase',education:'Education',income:'Investment income',wealth_preservation:'Wealth preservation',emergency_reserve:'Emergency reserve'};const fr:Record<string,string>={growth:'Croissance à long terme',retirement:'Retraite',house_purchase:'Achat d’une propriété',major_purchase:'Achat important',education:'Études',income:'Revenu de placement',wealth_preservation:'Préservation du patrimoine',emergency_reserve:'Fonds d’urgence'};const map=locale==="fr"?fr:en;return value?map[value]||value.replaceAll('_',' '):locale==="fr"?'Objectif de placement':'Investment goal'}
function horizonLabel(value:string|null|undefined,locale:"en"|"fr"="en"){const en:Record<string,string>={lt_1y:'Less than 1 year','1_3y':'1–3 years','3_5y':'3–5 years','5_10y':'5–10 years',gt_10y:'10+ years'};const fr:Record<string,string>={lt_1y:'Moins de 1 an','1_3y':'1 à 3 ans','3_5y':'3 à 5 ans','5_10y':'5 à 10 ans',gt_10y:'10 ans et plus'};const map=locale==="fr"?fr:en;return value?map[value]||value.replaceAll('_',' '):locale==="fr"?'Horizon non défini':'Horizon not set'}
function friendlyAuthError(value:string,locale:"en"|"fr"="en"){if(/expired|otp/i.test(value))return locale==="fr"?'Ce lien de connexion a expiré. Demandez un nouveau lien sécurisé.':'That sign-in link has expired. Request a new secure link.';if(/rate limit|too many/i.test(value))return locale==="fr"?'Trop de tentatives par courriel. Attendez une minute puis réessayez.':'Too many email attempts. Wait a minute and try again.';return value}
function personalFromState(state:AppState|null):PersonalizationProfile|null{const context=state?.report?.investment_context||state?.dna?.investment_context;return normalizePersonalization({first_name:context?.first_name,age:context?.age})}