import Link from 'next/link';

export default function ResearchAndLimitations(){return <section className="section"><div className="container narrow">
  <div className="eyebrow">Research & limitations</div><h1>What Investing DNA is — and what it is not</h1>
  <div className="card"><h2>Research-stage compatibility tool</h2><p>Investing DNA is designed to help people understand their investing profile and compare that profile with the structure and risk characteristics of investments. The current assessment is a research candidate, not a validated psychometric diagnostic.</p><p>Compatibility scores describe how closely the information currently available about a fund lines up with the Investor DNA and investment context supplied to the platform. They are not expected-return forecasts, ratings of investment quality, or instructions to buy, sell or hold a security.</p></div>
  <div className="card"><h2>Safety comes before ranking</h2><p>The Match engine can pause ranking when key financial context is missing or when the stated situation indicates that a ranked ETF comparison should not be produced. It can also return no suitable option inside the current research universe rather than forcing a result.</p><p>Changing answers only to increase a Match score defeats the purpose of the tool. Scores should change because the investor's real circumstances change, the investment changes, or newer verified data becomes available.</p></div>
  <div className="card"><h2>Fund data has coverage limits</h2><p>Investing DNA distinguishes verified facts from partial research coverage. Some funds have deeper holdings, exposure and portfolio-characteristic data than others. Missing data remains unavailable rather than being converted to zero or inferred without a source.</p><p>Historical performance does not guarantee future results. Fund structures, fees, risk classifications and holdings can change.</p></div>
  <div className="card"><h2>Not a substitute for professional advice</h2><p>Investing DNA does not execute trades, hold client assets, or know every fact that may matter to an investment decision. Tax, legal, estate, debt, insurance and household considerations may require qualified professional advice.</p><p>The product is being piloted as an educational and research experience. Regulatory review remains a launch gate before any broader positioning as personalized investment advice.</p></div>
  <div className="actions"><Link className="btn" href="/privacy">Pilot privacy summary</Link><Link className="btn primary" href="/dna/assessment">Explore my Investor DNA</Link></div>
</div></section>}
