import Link from 'next/link';

export default function ResearchAndLimitations(){return <section className="section"><div className="container narrow">
  <div className="eyebrow">Research & limitations</div><h1>What Investor DNA is — and what it is not</h1>
  <div className="card"><h2>Research-stage compatibility platform</h2><p>Investor DNA is designed to help people understand their investing profile and research how that profile relates to the structure and risk characteristics of investments. The Investing DNA assessment is a research candidate, not a validated psychometric diagnostic.</p><p>Where DNA Match is enabled, compatibility scores describe how closely the information currently available about an ETF lines up with the saved Investing DNA and investment context supplied to the platform. They are not expected-return forecasts, ratings of investment quality, or instructions to buy, sell or hold a security.</p></div>
  <div className="card"><h2>Cross-asset research does not mean cross-asset advice</h2><p>Investor DNA can research representative ETFs, GICs, T-Bills, bonds and money-market structures through a shared Investment DNA language. Personalized DNA Match remains ETF-only in this phase. GICs, T-Bills, bonds, commercial paper and ABCP are research profiles until separate asset-specific Match models are designed and validated.</p><p>Individual stocks are intentionally outside the current V1 research scope.</p></div>
  <div className="card"><h2>Portfolio Blueprint is an asset-class scenario tool</h2><p>When a complete goal context is available, the report can show More Defensive, Core and More Growth asset-class scenarios using Equity, Fixed income and Cash only. Financial capacity and goal constraints can cap the amount of market exposure; the tool does not infer Canada/US/international weights or select a fund.</p><p>The current blueprint is a deterministic research rule set, not a validated portfolio optimizer or expected-return model. <Link href="/research/portfolio-blueprint"><strong>Read the Portfolio Blueprint methodology →</strong></Link></p></div>
  <div className="card"><h2>Safety comes before ranking</h2><p>The ETF Match engine can pause ranking when key financial context is missing or when the stated situation indicates that a ranked comparison should not be produced. It can also return no suitable option inside the current ETF research universe rather than forcing a result.</p><p>Changing answers only to increase a Match score defeats the purpose of the tool. Scores should change because the investor's real circumstances change, the investment changes, or newer verified data becomes available.</p></div>
  <div className="card"><h2>Investment data has coverage and freshness limits</h2><p>Investor DNA distinguishes verified facts from partial research coverage. ETFs can have different holdings, exposure and portfolio-characteristic depth; fixed-income and deposit products have different source and market-data constraints. Missing data remains unavailable rather than being converted to zero or inferred without a source.</p><p>Historical performance, current yields and posted deposit rates do not guarantee future results. Rates, prices, risk classifications, holdings and product terms can change. Research pages expose source and as-of information where available.</p><p><Link href="/research/product-risk"><strong>Read the Product Risk DNA methodology →</strong></Link></p></div>
  <div className="card"><h2>Not a substitute for professional advice</h2><p>Investor DNA does not execute trades, hold client assets, or know every fact that may matter to an investment decision. Tax, legal, estate, debt, insurance and household considerations may require qualified professional advice.</p><p>The product is being piloted as an educational and research experience. Regulatory review remains a launch gate before any broader positioning as personalized investment advice.</p></div>
  <div className="actions"><Link className="btn" href="/privacy">Pilot privacy summary</Link><Link className="btn primary" href="/dna/assessment">Discover my Investing DNA</Link></div>
</div></section>}
