"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useAccount} from '@/lib/use-account';
import {instrumentWatchlist,removeInstrument,SavedInstrument} from '@/lib/instruments';
export default function Watchlist(){
 const {user,loading:authLoading}=useAccount();const [items,setItems]=useState<SavedInstrument[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setItems([]);setError('');if(!user){setLoading(false);return;}setLoading(true);instrumentWatchlist().then(d=>{if(active)setItems(d.items)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return ()=>{active=false};},[user?.id,retry]);
 async function remove(id:string){if(busy)return;setBusy(id);setError('');try{await removeInstrument(id);setItems(xs=>xs.filter(x=>x.investment_id!==id))}catch(e){setError(e instanceof Error?e.message:'Unable to remove investment.')}finally{setBusy('')}}
 return <section className="section"><div className="container"><div className="eyebrow">Your saved research</div><h1>My watchlist</h1><p className="muted">Keep investments here and return to their research profile. ETF items can also show your DNA compatibility.</p>{authLoading||loading?<p>Loading your watchlist…</p>:!user?<div className="card"><h2>A place to come back to</h2><p>Create a free account to save investment research across visits and devices.</p><div className="actions"><Link className="btn primary" href="/profile?mode=signup">Create a free account</Link><Link className="btn" href="/profile">Sign in</Link><Link className="btn" href="/explore">Browse investments</Link></div></div>:<>{!items.length&&!error?<div className="card"><h2>Your watchlist is empty</h2><p>Open an investment and choose “Save to my watchlist” to keep it here.</p><Link className="btn primary" href="/explore">Explore investments</Link></div>:<div className="grid3">{items.map(x=><div className="card" key={x.investment_id}>{x.symbol&&<span className="pill">{x.symbol}</span>}<h2>{x.name}</h2><div className="actions"><Link className="btn primary" href={'/investment/'+x.investment_id}>View research</Link><button className="btn" disabled={!!busy} onClick={()=>remove(x.investment_id)}>{busy===x.investment_id?'Removing…':'Remove'}</button></div></div>)}</div>}<div className="actions"><Link href="/profile">My profile</Link><Link href="/explore">Explore more investments</Link></div></>}{error&&<div role="alert" className="notice"><p>{error}</p><button className="btn" onClick={()=>setRetry(x=>x+1)}>Retry</button></div>}</div></section>;
}
