create extension if not exists pgcrypto;

create table if not exists public.assessments (
  id uuid primary key default gen_random_uuid(),
  assessment_version text not null default 'DNA_V1.0',
  status text not null default 'in_progress' check (status in ('in_progress','completed','abandoned')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  question_id text not null,
  answer_value jsonb not null,
  answered_at timestamptz not null default now(),
  unique (assessment_id, question_id)
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  model_version text not null default 'DNA_V1.0',
  risk_tolerance numeric(5,2),
  risk_capacity numeric(5,2),
  archetype text,
  behavioral_profile jsonb not null default '{}'::jsonb,
  narrative jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (assessment_id, model_version)
);

create index if not exists idx_answers_assessment_id on public.answers(assessment_id);
create index if not exists idx_results_archetype on public.results(archetype);

alter table public.assessments enable row level security;
alter table public.answers enable row level security;
alter table public.results enable row level security;

comment on table public.assessments is 'Investing DNA assessment sessions. V1 stores model/version metadata for reproducibility.';
comment on table public.answers is 'Raw questionnaire responses. Preserve original answers so assessments can be rescored when the model evolves.';
comment on table public.results is 'Derived Investing DNA scores and narrative outputs, versioned independently from raw answers.';