BEGIN;
UPDATE public.question_bank q SET prompt_en=v.prompt_en FROM (VALUES
('RT01','Which investment feels most like you?'),
('RT02','An investment falls 20%, but your original reason for buying it is still valid. What would you most likely do?'),
('RT03','Which investment would you feel more comfortable choosing?'),
('RT04','Which statement sounds most like you as an investor?'),
('RT05','Your investment has not grown for 18 months, while other markets are going up. What would you most likely do?'),
('RT06','Imagine your portfolio could lose 15% in a bad year, but gain 25% in a good year. How comfortable would you be with that?'),
('RT07','The market suddenly falls 30%. What would you most likely do first?'),
('RT08','When choosing between a safer and a riskier investment, what matters most to you?'),
('RT09','An investment could temporarily lose 30%, but you still believe in its long-term potential. How willing would you be to invest?'),
('RT10','What best describes the level of investment risk you have knowingly taken in the past?'),
('RT07B','After a big loss, how likely are you to take less risk in future investments, even if your long-term goals stay the same?'),
('BD01','When you hear “high-risk investment,” what do you think of first?'),
('BD02','Two investments can both lose 20%. Does that mean they are equally risky?'),
('BD03','How confident are you in your own investment decisions?'),
('BD04','Over the long term, how often do you expect your investment decisions to beat the market?'),
('BD05','If you are 80% confident that a prediction is correct, how often do you expect to be right?'),
('BD06','When someone tells you about a big investment win, how much does it affect your own decisions?'),
('BD07','An investment has gone up 40% in the past year. Does that make you more interested in buying it?'),
('BD08','You bought an investment at $100 and it is now worth $60. When deciding what to do next, which number are you most likely to focus on?'),
('BD09','Your research supports an investment, but three trusted analysts disagree. What would you most likely do?'),
('BD10','You sell an investment, then it goes up 20%. How much would that regret affect your next investment decision?'),
('BD11','You have a large gain on an investment. What would you most likely do?'),
('BD12','New information goes against an investment you liked. What would you most likely do?'),
('BD13','How confident are you in your ability to understand financial and investment information?'),
('BD14','When the market moves a lot, how hard is it for you to stick to your plan?'),
('BD15','The market falls and creates a chance to buy an investment you have researched. What would make you most interested in buying?'),
('RC01','What is your approximate yearly household income?'),
('RC02','How stable is the household income you rely on most?'),
('RC03','About how much money do you have available to invest?'),
('RC04','How would you describe your current debt?'),
('RC05','How many months could your emergency savings cover your essential expenses?'),
('RC06','How many people depend on your income?'),
('RC07','If your investment portfolio fell 20%, how much would that affect your everyday life?'),
('RC08','If you made one investment, about what percentage of your total financial assets would it be?'),
('RC09','If this investment lost 20%, would you still have enough other savings or assets to cover a large unexpected expense?'),
('RC10','How safe and stable is the income you rely on most?')
) AS v(question_id,prompt_en) WHERE q.version='v1.3' AND q.question_id=v.question_id;
COMMIT;