create or replace function public.get_pilot_questionnaire(p_assessment_id uuid) returns jsonb language plpgsql security invoker set search_path=public as $$ declare v_version text; v_status text; v_questions jsonb; begin select questionnaire_version,status into v_version,v_status from assessments where id=p_assessment_id; if v_version is null then raise exception 'Assessment not found'; end if; if v_status <> 'in_progress' then raise exception 'Assessment is not in progress'; end if; select coalesce(jsonb_agg(jsonb_build_object('question_id',question_id,'section',section,'construct',construct,'question_type',question_type,'prompt_en',prompt_en,'prompt_fa',prompt_fa,'options',options,'sort_order',sort_order,'weight',weight,'score_direction',score_direction,'construct_role',construct_role) order by sort_order),'[]'::jsonb) into v_questions from question_bank where version=v_version and active; return jsonb_build_object('assessment_id',p_assessment_id,'questionnaire_version',v_version,'questions',v_questions); end $$;
create or replace function public.pilot_submit_assessment(p_assessment_id uuid) returns jsonb language plpgsql security invoker set search_path=public as $$ declare v_result jsonb; v_fp jsonb; v_narr jsonb; begin v_result:=calculate_investing_dna(p_assessment_id); v_fp:=calculate_investing_fingerprint(p_assessment_id); v_narr:=generate_investing_narrative(p_assessment_id); return jsonb_build_object('result',v_result,'fingerprint',v_fp,'narrative',v_narr); end $$;
revoke all on function public.get_pilot_questionnaire(uuid) from public,anon,authenticated;
revoke all on function public.pilot_submit_assessment(uuid) from public,anon,authenticated;
create or replace view public.v_pilot_api_contract with (security_invoker=true) as
select 'start'::text action,'Create participant after consent and create one linked assessment.'::text purpose,'["cohort_code","consent_version"]'::jsonb input_contract,'["participant_id","anonymous_code","assessment_id","questionnaire_version","model_version"]'::jsonb output_contract
union all select 'questionnaire','Return active versioned questions for an in-progress assessment.','["assessment_id"]'::jsonb,'["assessment_id","questionnaire_version","questions"]'::jsonb
union all select 'save_answers','Upsert one or more answers; incomplete submissions remain in progress.','["assessment_id","answers[]"]'::jsonb,'["saved"]'::jsonb
union all select 'submit','Run completion validation, DNA scoring, fingerprint and narrative.','["assessment_id"]'::jsonb,'["result","fingerprint","narrative"]'::jsonb;
revoke all on public.v_pilot_api_contract from anon,authenticated;