create table if not exists public.scoring_dimensions (
 id uuid primary key default gen_random_uuid(), version text not null, section text not null, dimension_key text not null, display_name text not null, weight numeric not null default 1, min_score numeric not null default 0, max_score numeric not null default 100, is_core boolean not null default false, created_at timestamptz not null default now(), unique(version,dimension_key));
create table if not exists public.archetype_rules (
 id uuid primary key default gen_random_uuid(), version text not null, tolerance_band text not null, capacity_band text not null, archetype_key text not null, display_name text not null, description text, min_tolerance numeric not null, max_tolerance numeric not null, min_capacity numeric not null, max_capacity numeric not null, created_at timestamptz not null default now(), unique(version,tolerance_band,capacity_band), unique(version,archetype_key));
alter table public.scoring_dimensions enable row level security;
alter table public.archetype_rules enable row level security;
revoke all on public.scoring_dimensions from anon,authenticated;
revoke all on public.archetype_rules from anon,authenticated;
insert into public.scoring_dimensions(version,section,dimension_key,display_name,weight,is_core) values
('v1','risk_tolerance','risk_preference','Risk Preference',1,true),('v1','risk_tolerance','loss_tolerance','Loss Tolerance',1.2,true),('v1','risk_tolerance','volatility_comfort','Volatility Comfort',1,true),('v1','risk_tolerance','risk_reward','Risk Reward Preference',1,true),('v1','risk_tolerance','emotional_reactivity','Emotional Reactivity',0.8,false),('v1','risk_tolerance','patience','Investment Patience',0.6,false),('v1','risk_tolerance','past_risk_behavior','Past Risk Behaviour',1,true),('v1','risk_tolerance','crash_response','Crash Response',1,true),
('v1','behavioral_dna','risk_perception','Risk Perception',1,false),('v1','behavioral_dna','self_confidence','Financial Self-Confidence',1,false),('v1','behavioral_dna','overconfidence','Overconfidence',1,false),('v1','behavioral_dna','calibration','Decision Calibration',1,false),('v1','behavioral_dna','social_influence','Social Influence',1,false),('v1','behavioral_dna','recency_bias','Recency Bias',1,false),('v1','behavioral_dna','anchoring','Anchoring',1,false),('v1','behavioral_dna','confirmation_bias','Confirmation Bias',1,false),('v1','behavioral_dna','regret_sensitivity','Regret Sensitivity',1,false),('v1','behavioral_dna','disposition_effect','Disposition Effect',1,false),('v1','behavioral_dna','adaptability','Adaptability',1,false),('v1','behavioral_dna','financial_self_efficacy','Financial Self-Efficacy',1,false),('v1','behavioral_dna','opportunity_sensitivity','Opportunity Sensitivity',1,false),
('v1','risk_capacity','income','Income',1,true),('v1','risk_capacity','income_stability','Income Stability',1.2,true),('v1','risk_capacity','investable_assets','Investable Assets',1.2,true),('v1','risk_capacity','debt','Debt Load',1,true),('v1','risk_capacity','emergency_reserve','Emergency Reserve',1.2,true),('v1','risk_capacity','dependents','Dependents',0.8,true),('v1','risk_capacity','loss_impact','Loss Impact',1.5,true),('v1','risk_capacity','concentration','Portfolio Concentration',1,true),('v1','risk_capacity','financial_resources','Other Financial Resources',0.8,true),('v1','risk_capacity','employment','Employment Stability',1,true)
on conflict(version,dimension_key) do nothing;
insert into public.archetype_rules(version,tolerance_band,capacity_band,archetype_key,display_name,description,min_tolerance,max_tolerance,min_capacity,max_capacity) values
('v1','low','low','VAULT','VAULT','Low willingness and low financial capacity.',0,33.3333,0,33.3333),('v1','low','medium','ANCHOR','ANCHOR','Low willingness and moderate financial capacity.',0,33.3333,33.3334,66.6666),('v1','low','high','COOLHAND','COOLHAND','Low willingness and high financial capacity.',0,33.3333,66.6667,100),('v1','medium','low','SCOUT','SCOUT','Moderate willingness and low financial capacity.',33.3334,66.6666,0,33.3333),('v1','medium','medium','MAVERICK','MAVERICK','Moderate willingness and moderate financial capacity.',33.3334,66.6666,33.3334,66.6666),('v1','medium','high','STRIKER','STRIKER','Moderate willingness and high financial capacity.',33.3334,66.6666,66.6667,100),('v1','high','low','HOTSHOT','HOTSHOT','High willingness and low financial capacity.',66.6667,100,0,33.3333),('v1','high','medium','HIGHROLLER','HIGHROLLER','High willingness and moderate financial capacity.',66.6667,100,33.3334,66.6666),('v1','high','high','JACKPOT','JACKPOT','High willingness and high financial capacity.',66.6667,100,66.6667,100)
on conflict(version,tolerance_band,capacity_band) do nothing;