create or replace function public.calculate_investment_match(p_assessment_id uuid)
returns jsonb language plpgsql security definer set search_path=public,extensions as $$
declare a record; r record; c record; i record; s record; v_rt numeric; v_rc numeric; v_total numeric; v_rtfit numeric; v_rcfit numeric; v_riskfit numeric; v_alloc numeric; v_vol numeric; v_dd numeric; v_context numeric; v_target numeric; v_eq numeric; v_risk numeric; v_model text:='suitability-v2.3'; v_count int:=0; v_json jsonb:='[]'::jsonb; v_reasons jsonb; v_strengths jsonb; v_cautions jsonb; v_fit text; v_horizon_months int:=null; v_liquidity_score numeric:=50; v_return_score numeric:=50; v_loss_score numeric:=50; v_goal_score numeric:=50;
begin
 select * into a from assessments where id=p_assessment_id; if not found then raise exception 'assessment_not_found'; end if;
 select * into r from results where assessment_id=p_assessment_id and risk_tolerance is not null and risk_capacity is not null order by created_at desc limit 1; if not found then raise exception 'dna_result_not_found'; end if;
 v_rt:=r.risk_tolerance; v_rc:=r.risk_capacity; v_target:=greatest(0,least(100,v_rt*.60+v_rc*.40));
 select * into c from investment_context where assessment_id=p_assessment_id order by updated_at desc limit 1;
 if c.id is not null then
   v_horizon_months:=case when lower(c.time_horizon) like '%under_2%' then 18 when lower(c.time_horizon) like '%1_3%' then 30 when lower(c.time_horizon) like '%3_5%' then 48 when lower(c.time_horizon) like '%5%' or lower(c.time_horizon) like '%long%' then 72 else 48 end;
   v_liquidity_score:=case when lower(c.liquidity_need) like '%high%' then 85 when lower(c.liquidity_need) like '%medium%' then 60 else 30 end;
   v_return_score:=case when lower(c.required_return) like '%preserve%' then 25 when lower(c.required_return) like '%moderate%' then 55 when lower(c.required_return) like '%maximum%' or lower(c.required_return) like '%high%' then 90 else 50 end;
   v_loss_score:=case when lower(c.loss_consequence) like '%severe%' or lower(c.loss_consequence) like '%critical%' then 20 when lower(c.loss_consequence) like '%meaningful%' then 50 when lower(c.loss_consequence) like '%manageable%' then 75 else 50 end;
   v_goal_score:=case when lower(c.goal) like '%house%' or lower(c.goal) like '%education%' or lower(c.goal) like '%emergency%' then 25 when lower(c.goal) like '%income%' then 55 when lower(c.goal) like '%growth%' or lower(c.goal) like '%retirement%' then 80 else 50 end;
 end if;
 delete from investment_match_results where assessment_id=p_assessment_id and model_version=v_model;
 for i in select * from v_investment_detail where data_quality_status='verified' order by symbol loop
   select * into s from investment_suitability_profiles_v2 where investment_id=i.id and model_version='suitability-v2.0' limit 1;
   v_risk:=coalesce(s.normalized_risk_score,55);
   v_rtfit:=greatest(0,100-abs(v_rt-v_risk)*1.15); v_rcfit:=greatest(0,100-greatest(0,v_risk-v_rc)*1.75-greatest(0,v_rc-v_risk)*.35); v_riskfit:=v_rtfit*.60+v_rcfit*.40;
   v_eq:=case when i.profile_target_allocation ? 'equity' then (i.profile_target_allocation->>'equity')::numeric else null end;
   v_alloc:=case when v_eq is not null then greatest(0,100-abs(v_eq-v_target)*1.10) else 65 end;
   v_vol:=case when i.volatility_1y_pct is not null then greatest(0,100-abs(i.volatility_1y_pct-greatest(4,least(18,v_target*.12)))*4) else 50 end;
   v_dd:=case when i.max_drawdown_1y_pct is not null then greatest(0,100-abs(abs(i.max_drawdown_1y_pct)-greatest(8,least(30,v_target*.22)))*2.5) else 50 end;
   v_context:=100;
   v_reasons:='[]'::jsonb; v_strengths:='[]'::jsonb; v_cautions:='[]'::jsonb;
   if c.id is null then v_context:=70; v_cautions:=v_cautions||jsonb_build_array('Investment context has not been provided; this match is primarily DNA-based.');
   else
     if v_horizon_months < s.minimum_horizon_months then v_context:=v_context-35; v_cautions:=v_cautions||jsonb_build_array('Your stated time horizon is shorter than this strategy typically requires.'); else v_context:=v_context+0; v_reasons:=v_reasons||jsonb_build_array('Your time horizon is compatible with this strategy.'); end if;
     if v_liquidity_score>=80 and coalesce(v_eq,0)>=80 then v_context:=v_context-20; v_cautions:=v_cautions||jsonb_build_array('High liquidity needs conflict with high equity exposure.'); end if;
     if v_loss_score<=25 and v_risk>=72 then v_context:=v_context-20; v_cautions:=v_cautions||jsonb_build_array('The potential consequences of loss make this risk level less suitable.'); end if;
     if v_goal_score<=30 and coalesce(v_eq,0)>=80 then v_context:=v_context-15; v_cautions:=v_cautions||jsonb_build_array('Your goal emphasizes capital preservation, while this strategy emphasizes growth.'); end if;
     if v_return_score>=80 and coalesce(v_eq,0)>=60 then v_reasons:=v_reasons||jsonb_build_array('The strategy provides meaningful growth exposure consistent with your return objective.'); end if;
     if v_goal_score>=70 and coalesce(v_eq,0)>=60 then v_strengths:=v_strengths||jsonb_build_array('The growth orientation is compatible with your stated objective.'); end if;
     if v_liquidity_score<=40 and coalesce(v_eq,0)<=60 then v_strengths:=v_strengths||jsonb_build_array('The allocation is less dependent on high equity exposure, supporting lower liquidity stress.'); end if;
   end if;
   v_context:=greatest(0,least(100,v_context));
   v_total:=least(100,greatest(0,v_riskfit*.50+v_alloc*.15+v_vol*.08+v_dd*.07+v_context*.20));
   v_fit:=case when v_total>=85 then 'Strong fit' when v_total>=70 then 'Good fit' when v_total>=55 then 'Moderate fit' else 'Lower fit' end;
   insert into investment_match_results(assessment_id,investment_id,model_version,match_score,risk_tolerance_fit,risk_capacity_fit,risk_band,rationale,explanation)
   values(p_assessment_id,i.id,v_model,round(v_total,2),round(v_rtfit,2),round(v_rcfit,2),i.risk_level,jsonb_build_object('engine',v_model,'signal_type','context_aware_compatibility','not_investment_advice',true),jsonb_build_object('fit_label',v_fit,'summary',case when v_total>=85 then 'Strong alignment with your Investor DNA and current investment context.' when v_total>=70 then 'Good alignment with your Investor DNA and current investment context.' when v_total>=55 then 'Some alignment, but important trade-offs remain given your current context.' else 'Limited alignment with your Investor DNA and current investment context.' end,'why_it_fits',v_reasons,'strengths',v_strengths,'watchouts',v_cautions,'scores',jsonb_build_object('overall',round(v_total,2),'risk_fit',round(v_riskfit,2),'allocation_fit',round(v_alloc,2),'volatility_fit',round(v_vol,2),'drawdown_fit',round(v_dd,2),'context_fit',round(v_context,2)),'context',jsonb_build_object('horizon_months',v_horizon_months,'liquidity_score',v_liquidity_score,'return_objective_score',v_return_score,'loss_consequence_score',v_loss_score,'goal_score',v_goal_score),'dna',jsonb_build_object('risk_tolerance',round(v_rt,2),'risk_capacity',round(v_rc,2),'target_equity_pct',round(v_target,2)),'investment',jsonb_build_object('risk_band',i.risk_level,'equity_pct',v_eq,'minimum_horizon_months',s.minimum_horizon_months),'disclaimer','Compatibility signal only; not investment advice.'));
   v_json:=v_json||jsonb_build_array(jsonb_build_object('investment_id',i.id,'symbol',i.symbol,'match_score',round(v_total,2),'fit_label',v_fit,'explanation',jsonb_build_object('why_it_fits',v_reasons,'strengths',v_strengths,'watchouts',v_cautions))); v_count:=v_count+1;
 end loop;
 return jsonb_build_object('model_version',v_model,'assessment_id',p_assessment_id,'count',v_count,'context_applied',c.id is not null,'results',v_json);
end; $$;
revoke all on function public.calculate_investment_match(uuid) from anon,authenticated; grant execute on function public.calculate_investment_match(uuid) to service_role;
create or replace function public.get_investment_recommendations(p_assessment_id uuid,p_limit int default 10) returns jsonb language plpgsql security definer set search_path=public,extensions as $$ declare v_limit int:=greatest(1,least(coalesce(p_limit,10),25)); v_model text:='suitability-v2.3'; v_count int; v_top jsonb; v_alt jsonb; v_consider jsonb; v_mismatch jsonb; begin if not exists(select 1 from assessments where id=p_assessment_id) then raise exception 'assessment_not_found'; end if; select count(*) into v_count from investment_match_results where assessment_id=p_assessment_id and model_version=v_model; if v_count=0 then raise exception 'match_results_not_found'; end if; select coalesce(jsonb_agg(to_jsonb(x) order by x.match_rank),'[]') into v_top from (select match_rank,symbol,name,match_score,recommendation_tier,risk_band,explanation from v_investment_match_ranked where assessment_id=p_assessment_id and model_version=v_model and recommendation_tier='top_match' order by match_rank limit v_limit)x; select coalesce(jsonb_agg(to_jsonb(x) order by x.match_rank),'[]') into v_alt from (select match_rank,symbol,name,match_score,recommendation_tier,risk_band,explanation from v_investment_match_ranked where assessment_id=p_assessment_id and model_version=v_model and recommendation_tier='alternative' order by match_rank limit v_limit)x; select coalesce(jsonb_agg(to_jsonb(x) order by x.match_rank),'[]') into v_consider from (select match_rank,symbol,name,match_score,recommendation_tier,risk_band from v_investment_match_ranked where assessment_id=p_assessment_id and model_version=v_model and recommendation_tier='consider' order by match_rank limit v_limit)x; select coalesce(jsonb_agg(to_jsonb(x) order by x.match_rank),'[]') into v_mismatch from (select match_rank,symbol,name,match_score,recommendation_tier,risk_band from v_investment_match_ranked where assessment_id=p_assessment_id and model_version=v_model and recommendation_tier='mismatch' order by match_rank limit v_limit)x; return jsonb_build_object('model_version',v_model,'assessment_id',p_assessment_id,'universe_count',v_count,'top_matches',v_top,'alternatives',v_alt,'consider',v_consider,'mismatch',v_mismatch,'disclaimer','Compatibility signals based on Investor DNA, investment context, and available investment data; not investment advice.'); end; $$;
revoke all on function public.get_investment_recommendations(uuid,int) from public,anon,authenticated; grant execute on function public.get_investment_recommendations(uuid,int) to service_role;