BEGIN;

DELETE FROM public.question_bank WHERE version='v1.3';
INSERT INTO public.question_bank
(question_id, version, section, construct, question_type, prompt_en, prompt_fa, options, scoring, sort_order, active, weight, score_direction, construct_role)
SELECT question_id, 'v1.3', section, construct, question_type, prompt_en, prompt_fa, options, scoring, sort_order, active, weight, score_direction, construct_role
FROM public.question_bank
WHERE version='v1.2' AND active=true;

WITH v(question_id,prompt_en,prompt_fa,options,scoring,weight) AS (
VALUES
('RT01','Which investment feels most like you?','کدام گزینه بیشتر شبیه سبک سرمایه‌گذاری شماست؟','[{"label":"6% expected return, very low volatility","value":"A"},{"label":"10% expected return, moderate volatility","value":"B"},{"label":"16% expected return, high volatility","value":"C"},{"label":"25% expected return, very high volatility","value":"D"}]'::jsonb,'{"A":20,"B":45,"C":75,"D":100}'::jsonb,1),
('RT02','An investment falls 20%, but nothing has changed in your original investment thesis. What would you most likely do?','ارزش یک سرمایه‌گذاری ۲۰٪ افت کرده، اما دلیل و تحلیل اولیه شما هنوز معتبر است. احتمالاً چه کار می‌کنید؟','[{"label":"Sell most or all","value":"A"},{"label":"Sell some to reduce risk","value":"B"},{"label":"Hold and wait","value":"C"},{"label":"Buy more","value":"D"}]'::jsonb,'{"A":10,"B":35,"C":70,"D":100}'::jsonb,1.2),
('RT03','Which investment would you feel more comfortable choosing?','کدام سرمایه‌گذاری را با خیال راحت‌تری انتخاب می‌کنید؟','[{"label":"95% chance to gain $4,000; 5% chance to lose $500","value":"A"},{"label":"80% chance to gain $6,000; 20% chance to lose $2,000","value":"B"},{"label":"65% chance to gain $10,000; 35% chance to lose $5,000","value":"C"},{"label":"50% chance to gain $16,000; 50% chance to lose $8,000","value":"D"}]'::jsonb,'{"A":20,"B":45,"C":75,"D":100}'::jsonb,1),
('RT04','Which statement sounds most like you as an investor?','کدام جمله بیشتر شبیه شما به‌عنوان یک سرمایه‌گذار است؟','[{"label":"Protecting my capital comes first","value":"A"},{"label":"I accept some risk for better returns","value":"B"},{"label":"I am comfortable with significant volatility","value":"C"},{"label":"I accept large temporary losses for substantial upside","value":"D"}]'::jsonb,'{"A":15,"B":45,"C":75,"D":100}'::jsonb,1),
('RT05','Your investment has been flat for 18 months while other markets rise. What are you most likely to do?','سرمایه‌گذاری شما ۱۸ ماه بدون رشد مانده، در حالی که بازارهای دیگر رشد کرده‌اند. احتمالاً چه واکنشی نشان می‌دهید؟','[{"label":"Sell and move on","value":"A"},{"label":"Review it and may reduce the position","value":"B"},{"label":"Stay invested if the original thesis is still valid","value":"C"},{"label":"Stay invested and consider adding if the thesis is still strong","value":"D"}]'::jsonb,'{"A":25,"B":45,"C":75,"D":90}'::jsonb,0.4),
('RT06','Imagine your portfolio could lose up to 15% in a bad year, but could gain up to 25% in a good year. How comfortable would you be with that?','فرض کنید پرتفوی شما در یک سال بد ممکن است تا ۱۵٪ افت کند و در یک سال خوب تا ۲۵٪ رشد کند. چقدر با این وضعیت راحت هستید؟','[{"label":"Very uncomfortable","value":"A"},{"label":"Somewhat uncomfortable","value":"B"},{"label":"Comfortable","value":"C"},{"label":"Very comfortable","value":"D"}]'::jsonb,'{"A":10,"B":40,"C":75,"D":100}'::jsonb,1),
('RT07','The market suddenly drops 30%. What is your most likely first reaction?','بازار ناگهان ۳۰٪ سقوط می‌کند. اولین واکنش محتمل شما چیست؟','[{"label":"Sell quickly to stop further losses","value":"A"},{"label":"Wait and reassess before acting","value":"B"},{"label":"Hold through the decline","value":"C"},{"label":"Look for opportunities to buy","value":"D"}]'::jsonb,'{"A":10,"B":45,"C":75,"D":100}'::jsonb,1),
('RT08','When choosing between a safer investment and a riskier one, what matters most to you?','وقتی بین یک سرمایه‌گذاری امن‌تر و یک گزینه پرریسک‌تر انتخاب می‌کنید، چه چیزی برایتان مهم‌تر است؟','[{"label":"Avoiding the possibility of loss","value":"A"},{"label":"Balancing risk and return","value":"B"},{"label":"Maximizing expected return","value":"C"},{"label":"Capturing the biggest possible upside","value":"D"}]'::jsonb,'{"A":15,"B":50,"C":80,"D":100}'::jsonb,1),
('RT09','If an investment could temporarily lose 30% but you still believed strongly in its long-term potential, how willing would you be to invest?','اگر یک سرمایه‌گذاری ممکن بود موقتاً ۳۰٪ افت کند، اما همچنان به پتانسیل بلندمدت آن باور داشتید، چقدر حاضر بودید در آن سرمایه‌گذاری کنید؟','[{"label":"I would avoid it","value":"A"},{"label":"I would consider only a small amount","value":"B"},{"label":"I would be comfortable investing if the long-term case remained strong","value":"C"},{"label":"I would seriously consider it despite the potential loss","value":"D"}]'::jsonb,'{"A":15,"B":40,"C":75,"D":100}'::jsonb,1),
('RT10','Which best describes the investment risk you have knowingly accepted in the past?','کدام گزینه بهترین توصیف از ریسکی است که در گذشته آگاهانه در سرمایه‌گذاری پذیرفته‌اید؟','[{"label":"I usually avoided large risks","value":"A"},{"label":"I sometimes took more risk than I later felt comfortable with","value":"B"},{"label":"I have knowingly accepted substantial investment risk","value":"C"},{"label":"I have knowingly accepted very high risk for higher potential returns","value":"D"}]'::jsonb,'{"A":15,"B":45,"C":75,"D":100}'::jsonb,1),
('RT07B','After experiencing a major loss, how likely would you be to reduce your future investment risk even if your long-term goals had not changed?','بعد از تجربه یک زیان قابل‌توجه، حتی اگر اهداف بلندمدت شما تغییری نکرده باشند، چقدر احتمال دارد ریسک سرمایه‌گذاری‌های بعدی خود را کاهش دهید؟','[{"label":"Very likely","value":"A"},{"label":"Somewhat likely","value":"B"},{"label":"Unlikely","value":"C"},{"label":"Very unlikely","value":"D"}]'::jsonb,'{"A":10,"B":40,"C":75,"D":100}'::jsonb,0.5),
('BD01','When you hear “high-risk investment,” what comes to mind first?','وقتی عبارت «سرمایه‌گذاری پرریسک» را می‌شنوید، اولین چیزی که به ذهنتان می‌رسد چیست؟','[{"label":"A high chance of losing money","value":"A"},{"label":"Large price swings","value":"B"},{"label":"A high level of uncertainty","value":"C"},{"label":"A potentially missed opportunity if I avoid it","value":"D"}]'::jsonb,'{"A":25,"B":50,"C":70,"D":90}'::jsonb,1),
('BD02','If two investments can both lose 20%, does that automatically mean they have the same level of risk?','اگر دو سرمایه‌گذاری هر دو ممکن است ۲۰٪ افت کنند، آیا این به‌تنهایی یعنی هر دو دقیقاً به یک اندازه پرریسک هستند؟','[{"label":"Yes","value":"A"},{"label":"Not necessarily","value":"B"},{"label":"No — risk can also depend on other factors","value":"C"}]'::jsonb,'{"A":20,"B":70,"C":100}'::jsonb,1),
('BD03','How confident are you in your own investment decision-making?','چقدر به توانایی خودتان در تصمیم‌گیری سرمایه‌گذاری اعتماد دارید؟','[]'::jsonb,'{"scale":{"max":10,"min":0,"direction":"direct"}}'::jsonb,1),
('BD04','Over the long run, how often do you expect your investment decisions to outperform the market?','در بلندمدت، انتظار دارید تصمیم‌های سرمایه‌گذاری شما چند وقت یک‌بار بهتر از بازار عمل کنند؟','[]'::jsonb,'{"scale":{"max":10,"min":0,"direction":"direct"}}'::jsonb,1),
('BD05','If you are 80% confident that an investment prediction will be correct, how often do you expect to actually be right?','اگر ۸۰٪ مطمئن باشید که یک پیش‌بینی سرمایه‌گذاری درست است، انتظار دارید در عمل چند درصد مواقع درست از آب دربیاید؟','[{"label":"Around 50%","value":"A"},{"label":"Around 65%","value":"B"},{"label":"Around 80%","value":"C"},{"label":"Around 95%","value":"D"}]'::jsonb,'{"A":20,"B":55,"C":100,"D":20}'::jsonb,1),
('BD06','When you hear someone describe a big investment win, how much does it influence your own investment decisions?','وقتی کسی از یک موفقیت بزرگ سرمایه‌گذاری صحبت می‌کند، این موضوع چقدر روی تصمیم‌های سرمایه‌گذاری شما اثر می‌گذارد؟','[]'::jsonb,'{"scale":{"max":10,"min":0,"direction":"direct"}}'::jsonb,1),
('BD07','An investment has risen 40% over the past year. Does its recent performance make you more interested in buying it?','یک سرمایه‌گذاری در یک سال گذشته ۴۰٪ رشد کرده است. آیا همین عملکرد اخیر باعث می‌شود بیشتر به خرید آن علاقه‌مند شوید؟','[{"label":"Much less interested","value":"A"},{"label":"About the same","value":"B"},{"label":"Somewhat more interested","value":"C"},{"label":"Much more interested","value":"D"}]'::jsonb,'{"A":10,"B":40,"C":70,"D":100}'::jsonb,1),
('BD08','You bought an investment at $100 and it is now $60. When deciding what to do next, which number are you most likely to focus on?','یک سرمایه‌گذاری را با قیمت ۱۰۰ دلار خریده‌اید و حالا قیمت آن ۶۰ دلار است. هنگام تصمیم‌گیری درباره قدم بعدی، بیشتر روی کدام عدد تمرکز می‌کنید؟','[{"label":"The $100 purchase price","value":"A"},{"label":"The $60 current price","value":"B"},{"label":"The investment’s current fundamental value","value":"C"}]'::jsonb,'{"A":100,"B":55,"C":10}'::jsonb,1),
('BD09','Your data supports an investment, but three credible analysts disagree. Which response is most like you?','داده‌های شما از یک سرمایه‌گذاری حمایت می‌کنند، اما سه تحلیلگر معتبر با شما مخالف‌اند. کدام واکنش بیشتر شبیه شماست؟','[{"label":"I mostly look for information that supports my view","value":"A"},{"label":"I consider their views but mainly focus on evidence supporting my thesis","value":"B"},{"label":"I actively test my thesis against their arguments","value":"C"},{"label":"I pause and seek more evidence before deciding","value":"D"}]'::jsonb,'{"A":100,"B":65,"C":15,"D":5}'::jsonb,1),
('BD10','After selling an investment and then watching it rise 20%, how strongly would that regret affect your next investment decision?','اگر یک سرمایه‌گذاری را بفروشید و بعد شاهد رشد ۲۰٪ آن باشید، این پشیمانی چقدر روی تصمیم سرمایه‌گذاری بعدی شما اثر می‌گذارد؟','[]'::jsonb,'{"scale":{"max":10,"min":0,"direction":"direct"}}'::jsonb,1),
('BD11','You are sitting on a large investment gain. What are you most likely to do?','یک سرمایه‌گذاری شما سود قابل‌توجهی ساخته است. احتمالاً چه کار می‌کنید؟','[{"label":"Sell to lock in the gain","value":"A"},{"label":"Sell part and keep part","value":"B"},{"label":"Hold if the investment case remains strong","value":"C"},{"label":"Add if the outlook has improved","value":"D"}]'::jsonb,'{"A":100,"B":65,"C":20,"D":10}'::jsonb,1),
('BD12','New evidence contradicts an investment you previously liked. What is your reaction?','شواهد جدید با سرمایه‌گذاری‌ای که قبلاً دوست داشتید در تضاد است. واکنش شما چیست؟','[{"label":"I usually defend my original view","value":"A"},{"label":"I become cautious","value":"B"},{"label":"I reassess the investment case","value":"C"},{"label":"I change course when the evidence warrants it","value":"D"}]'::jsonb,'{"A":10,"B":45,"C":80,"D":100}'::jsonb,1),
('BD13','How capable do you feel of understanding financial and investment information?','چقدر خودتان را در درک اطلاعات مالی و سرمایه‌گذاری توانمند می‌دانید؟','[]'::jsonb,'{"scale":{"max":10,"min":0,"direction":"direct"}}'::jsonb,1),
('BD14','During major market moves, how difficult is it for you to stick to a pre-planned strategy?','در نوسانات شدید بازار، پایبندی به استراتژی از پیش تعیین‌شده برای شما چقدر دشوار است؟','[]'::jsonb,'{"scale":{"max":10,"min":0,"direction":"direct"}}'::jsonb,1),
('BD15','A market sell-off creates an opportunity in an investment you have researched. What makes you most interested in buying?','در زمان ریزش بازار، در یک سرمایه‌گذاری که درباره‌اش تحقیق کرده‌اید فرصت جدیدی ایجاد می‌شود. چه چیزی بیشتر شما را به خرید آن علاقه‌مند می‌کند؟','[{"label":"I would rather wait until uncertainty is lower","value":"A"},{"label":"The valuation looks attractive relative to the fundamentals","value":"B"},{"label":"The potential long-term return is compelling","value":"C"},{"label":"The sell-off creates a chance to act while others are fearful","value":"D"}]'::jsonb,'{"A":20,"B":55,"C":80,"D":100}'::jsonb,1),
('RC01','What is your approximate annual household income?','درآمد سالانه تقریبی خانوار شما چقدر است؟','[{"label":"Under $40,000","value":"A"},{"label":"$40,000–$79,999","value":"B"},{"label":"$80,000–$149,999","value":"C"},{"label":"$150,000+","value":"D"}]'::jsonb,'{"A":20,"B":45,"C":75,"D":100}'::jsonb,1),
('RC02','How stable is the household income you rely on most?','درآمد خانواری که بیشترین اتکا را به آن دارید چقدر باثبات است؟','[{"label":"Highly variable or uncertain","value":"A"},{"label":"Somewhat variable","value":"B"},{"label":"Mostly stable","value":"C"},{"label":"Very stable","value":"D"}]'::jsonb,'{"A":15,"B":40,"C":75,"D":100}'::jsonb,1.2),
('RC03','Approximately how much do you have in investable financial assets?','تقریباً چه میزان دارایی مالی قابل سرمایه‌گذاری دارید؟','[{"label":"Under $25,000","value":"A"},{"label":"$25,000–$99,999","value":"B"},{"label":"$100,000–$499,999","value":"C"},{"label":"$500,000+","value":"D"}]'::jsonb,'{"A":15,"B":40,"C":75,"D":100}'::jsonb,1.2),
('RC04','How would you describe your current debt burden?','وضعیت بدهی فعلی خود را چگونه توصیف می‌کنید؟','[{"label":"High — it significantly limits what I can afford to invest","value":"A"},{"label":"Moderate","value":"B"},{"label":"Low","value":"C"},{"label":"Very low or no significant debt","value":"D"}]'::jsonb,'{"A":10,"B":40,"C":75,"D":100}'::jsonb,1),
('RC05','How long could your emergency savings cover essential expenses?','پس‌انداز اضطراری شما چند ماه هزینه‌های ضروری را پوشش می‌دهد؟','[{"label":"Less than 1 month","value":"A"},{"label":"1–3 months","value":"B"},{"label":"3–6 months","value":"C"},{"label":"More than 6 months","value":"D"}]'::jsonb,'{"A":10,"B":40,"C":75,"D":100}'::jsonb,1.2),
('RC06','How many people financially depend on your income?','چند نفر از نظر مالی به درآمد شما وابسته‌اند؟','[{"label":"4 or more","value":"A"},{"label":"2–3","value":"B"},{"label":"1","value":"C"},{"label":"None","value":"D"}]'::jsonb,'{"A":20,"B":45,"C":75,"D":100}'::jsonb,0.8),
('RC07','If your investment portfolio fell 20%, how would that affect your everyday life?','اگر پرتفوی شما ۲۰٪ افت کند، این افت چه اثری بر زندگی روزمره شما خواهد داشت؟','[{"label":"I might struggle to cover essential expenses","value":"A"},{"label":"I would need to make significant lifestyle changes","value":"B"},{"label":"It would be uncomfortable but manageable","value":"C"},{"label":"It would have little effect on my lifestyle","value":"D"}]'::jsonb,'{"A":5,"B":35,"C":70,"D":100}'::jsonb,1.5),
('RC08','If you made a single investment, roughly what percentage of your total financial assets would it represent?','اگر یک سرمایه‌گذاری انجام دهید، تقریباً چه درصدی از کل دارایی‌های مالی شما را تشکیل می‌دهد؟','[{"label":"More than 50%","value":"A"},{"label":"25%–50%","value":"B"},{"label":"10%–25%","value":"C"},{"label":"Less than 10%","value":"D"}]'::jsonb,'{"A":10,"B":40,"C":75,"D":100}'::jsonb,0.7),
('RC09','If this investment lost 20%, would you still have enough other savings or assets to handle a major unexpected expense?','اگر این سرمایه‌گذاری ۲۰٪ زیان بدهد، آیا همچنان پس‌انداز یا دارایی کافی دیگری برای پوشش یک هزینه پیش‌بینی‌نشده بزرگ خواهید داشت؟','[{"label":"No","value":"A"},{"label":"Probably not","value":"B"},{"label":"Probably yes","value":"C"},{"label":"Definitely yes","value":"D"}]'::jsonb,'{"A":15,"B":45,"C":75,"D":100}'::jsonb,0.8),
('RC10','How secure is the income source you rely on most?','منبع درآمدی که بیشترین اتکا را به آن دارید چقدر امن و باثبات است؟','[{"label":"Uncertain or at significant risk","value":"A"},{"label":"Somewhat uncertain","value":"B"},{"label":"Generally secure","value":"C"},{"label":"Highly secure","value":"D"}]'::jsonb,'{"A":15,"B":40,"C":75,"D":100}'::jsonb,1)
)
UPDATE public.question_bank q
SET prompt_en=v.prompt_en, prompt_fa=v.prompt_fa, options=v.options, scoring=v.scoring, weight=v.weight
FROM v
WHERE q.version='v1.3' AND q.question_id=v.question_id;

-- Keep the calibrated V1.2 zone boundaries for V1.3 until pilot data supports a new calibration.
UPDATE public.assessments
SET questionnaire_version=questionnaire_version
WHERE false;

COMMIT;