insert into investment_data_sources (investment_id,source_name,source_type,source_url,metric_scope,retrieved_at,source_version,notes)
select i.id,'MarketScreener','secondary','https://www.marketscreener.com/','holdings',now(),'2026-09','Top holdings cross-check; BlackRock remains primary source for fund profile and metrics.'
from investments i where i.symbol in ('XEQT','XGRO','XBAL','XIC','XUU') and not exists (select 1 from investment_data_sources s where s.investment_id=i.id and s.source_name='MarketScreener' and s.metric_scope='holdings');

insert into investment_holdings (investment_id,as_of_date,holding_symbol,holding_name,sector,asset_type,weight_pct,source_id)
select i.id,v.as_of_date,v.holding_symbol,v.holding_name,v.sector,v.asset_type,v.weight_pct,s.id
from investments i join (values
('XEQT','2026-09-10'::date,'NVDA','NVIDIA Corporation','Technology','equity',2.94::numeric),('XEQT','2026-09-10'::date,'AAPL','Apple Inc.','Technology','equity',2.61::numeric),('XEQT','2026-09-10'::date,'MSFT','Microsoft Corporation','Technology','equity',2.33::numeric),('XEQT','2026-09-10'::date,'RY','Royal Bank of Canada','Financials','equity',1.96::numeric),('XEQT','2026-09-10'::date,'SHOP','Shopify Inc.','Technology','equity',1.61::numeric),
('XGRO','2026-08-31'::date,'CAN-GOV','Government of Canada','Government Bonds','bond',9.31::numeric),('XGRO','2026-08-31'::date,'NVDA','NVIDIA Corporation','Technology','equity',2.55::numeric),('XGRO','2026-08-31'::date,'AAPL','Apple Inc.','Technology','equity',2.27::numeric),('XGRO','2026-08-31'::date,'TNOTE','U.S. Treasury Note','Government Bonds','bond',1.87::numeric),('XGRO','2026-08-31'::date,'MSFT','Microsoft Corporation','Technology','equity',1.85::numeric),
('XBAL','2026-07-31'::date,'AAPL','Apple Inc.','Technology','equity',1.89::numeric),('XBAL','2026-07-31'::date,'NVDA','NVIDIA Corporation','Technology','equity',1.82::numeric),('XBAL','2026-07-31'::date,'MSFT','Microsoft Corporation','Technology','equity',1.29::numeric),('XBAL','2026-07-31'::date,'RY','Royal Bank of Canada','Financials','equity',1.28::numeric),('XBAL','2026-07-31'::date,'AMZN','Amazon.com Inc.','Consumer Discretionary','equity',0.89::numeric),
('XIC','2026-07-31'::date,'RY','Royal Bank of Canada','Financials','equity',8.10::numeric),('XIC','2026-07-31'::date,'TD','Toronto-Dominion Bank','Financials','equity',5.52::numeric),('XIC','2026-07-31'::date,'SHOP','Shopify Inc.','Technology','equity',4.12::numeric),('XIC','2026-07-31'::date,'BMO','Bank of Montreal','Financials','equity',3.45::numeric),('XIC','2026-07-31'::date,'ENB','Enbridge Inc.','Energy','equity',3.34::numeric),
('XUU','2026-09-10'::date,'AAPL','Apple Inc.','Technology','equity',6.02::numeric),('XUU','2026-09-10'::date,'MSFT','Microsoft Corporation','Technology','equity',5.85::numeric),('XUU','2026-09-10'::date,'NVDA','NVIDIA Corporation','Technology','equity',5.42::numeric),('XUU','2026-09-10'::date,'AMZN','Amazon.com Inc.','Consumer Discretionary','equity',3.22::numeric),('XUU','2026-09-10'::date,'META','Meta Platforms Inc.','Technology','equity',1.96::numeric)
) v(sym,as_of_date,holding_symbol,holding_name,sector,asset_type,weight_pct) on v.sym=i.symbol join investment_data_sources s on s.investment_id=i.id and s.source_name='MarketScreener' and s.metric_scope='holdings'
on conflict (investment_id,as_of_date,holding_name) do update set holding_symbol=excluded.holding_symbol,sector=excluded.sector,asset_type=excluded.asset_type,weight_pct=excluded.weight_pct,source_id=excluded.source_id;