insert into public.investment_issuers(name,website,country_code)
values
 ('Government of Canada','https://www.canada.ca/','CA'),
 ('Royal Bank of Canada','https://www.rbcroyalbank.com/','CA'),
 ('Province of Ontario','https://www.ofina.on.ca/','CA'),
 ('Bell Canada','https://www.bce.ca/','CA')
on conflict (name) do update set website=excluded.website,country_code=excluded.country_code,updated_at=now();

insert into public.investments(symbol,name,legal_name,asset_type,issuer_id,category,subcategory,strategy,region,country_code,currency,exchange,description,is_active,is_featured,data_status)
values
 ('RBC-GIC-1Y-NR','RBC 1-Year Non-Redeemable GIC','Royal Bank of Canada Guaranteed-Return GIC','GIC',(select id from public.investment_issuers where name='Royal Bank of Canada'),'Guaranteed Deposit','Non-Redeemable','Fixed-rate term deposit','Canada','CA','CAD','DEPOSIT','A one-year fixed-rate GIC reference product. Principal and interest terms are contractual; access before maturity is restricted.',true,true,'verified_reference'),
 ('RBC-GIC-5Y-NR','RBC 5-Year Non-Redeemable GIC','Royal Bank of Canada Guaranteed-Return GIC','GIC',(select id from public.investment_issuers where name='Royal Bank of Canada'),'Guaranteed Deposit','Non-Redeemable','Fixed-rate term deposit','Canada','CA','CAD','DEPOSIT','A five-year fixed-rate GIC reference product that exchanges liquidity for a defined term and rate.',true,true,'verified_reference'),
 ('RBC-GIC-1Y-CASH','RBC 1-Year Cashable GIC','Royal Bank of Canada One-Year Cashable GIC','GIC',(select id from public.investment_issuers where name='Royal Bank of Canada'),'Guaranteed Deposit','Cashable','Cashable term deposit','Canada','CA','CAD','DEPOSIT','A one-year cashable GIC reference product designed to preserve principal while allowing earlier access subject to product terms.',true,true,'verified_reference'),
 ('RBC-GIC-3Y-RED','RBC 3-Year Redeemable GIC','Royal Bank of Canada Redeemable GIC','GIC',(select id from public.investment_issuers where name='Royal Bank of Canada'),'Guaranteed Deposit','Redeemable','Redeemable fixed-rate term deposit','Canada','CA','CAD','DEPOSIT','A three-year redeemable GIC reference product. Early redemption can change the rate actually received.',true,true,'verified_reference'),
 ('GOC-TBILL-3M','Government of Canada 3-Month T-Bill','Government of Canada 3-Month Treasury Bill Reference','T_BILL',(select id from public.investment_issuers where name='Government of Canada'),'Money Market','3 Month','Discount government security','Canada','CA','CAD','GOC','A short-term Government of Canada Treasury Bill reference based on the Bank of Canada secondary-market yield series.',true,true,'verified_reference'),
 ('GOC-TBILL-6M','Government of Canada 6-Month T-Bill','Government of Canada 6-Month Treasury Bill Reference','T_BILL',(select id from public.investment_issuers where name='Government of Canada'),'Money Market','6 Month','Discount government security','Canada','CA','CAD','GOC','A six-month Government of Canada Treasury Bill reference based on the Bank of Canada secondary-market yield series.',true,true,'verified_reference'),
 ('GOC-TBILL-1Y','Government of Canada 1-Year T-Bill','Government of Canada 1-Year Treasury Bill Reference','T_BILL',(select id from public.investment_issuers where name='Government of Canada'),'Money Market','1 Year','Discount government security','Canada','CA','CAD','GOC','A one-year Government of Canada Treasury Bill reference based on the Bank of Canada secondary-market yield series.',true,true,'verified_reference'),
 ('GOC-BOND-2Y','Government of Canada 2-Year Benchmark Bond','Government of Canada Benchmark Bond 2 Year','BOND',(select id from public.investment_issuers where name='Government of Canada'),'Government','Federal','Nominal fixed-rate bond','Canada','CA','CAD','GOC','Current two-year Government of Canada benchmark-bond reference used to illustrate short-duration sovereign fixed income.',true,true,'verified_reference'),
 ('GOC-BOND-5Y','Government of Canada 5-Year Benchmark Bond','Government of Canada 3.00% Sep 1 2031','BOND',(select id from public.investment_issuers where name='Government of Canada'),'Government','Federal','Nominal fixed-rate bond','Canada','CA','CAD','GOC','Current five-year Government of Canada benchmark-bond reference.',true,true,'verified_reference'),
 ('GOC-BOND-10Y','Government of Canada 10-Year Benchmark Bond','Government of Canada 3.25% Jun 1 2036','BOND',(select id from public.investment_issuers where name='Government of Canada'),'Government','Federal','Nominal fixed-rate bond','Canada','CA','CAD','GOC','Current ten-year Government of Canada benchmark-bond reference used to illustrate greater interest-rate sensitivity.',true,true,'verified_reference'),
 ('GOC-BOND-LONG','Government of Canada Long-Term Benchmark Bond','Government of Canada 3.50% Dec 1 2057','BOND',(select id from public.investment_issuers where name='Government of Canada'),'Government','Federal Long','Nominal fixed-rate bond','Canada','CA','CAD','GOC','Long-term Government of Canada benchmark-bond reference with substantially greater duration exposure than short bonds.',true,true,'verified_reference'),
 ('ON-BOND-2031','Province of Ontario 2.25% Bond due 2031','Province of Ontario DMTN253 2.25% Dec 2 2031','BOND',(select id from public.investment_issuers where name='Province of Ontario'),'Government','Provincial','Provincial fixed-rate bond','Canada','CA','CAD','OTC','A Province of Ontario Canadian-dollar bond reference illustrating provincial credit exposure.',true,true,'verified_reference'),
 ('BELL-M69-2036','Bell Canada 4.70% MTN due 2036','Bell Canada Series M-69 4.70% MTN Debenture','BOND',(select id from public.investment_issuers where name='Bell Canada'),'Corporate','Investment Grade Corporate Example','Corporate debenture','Canada','CA','CAD','OTC','A Bell Canada public Canadian MTN debenture reference illustrating single-issuer corporate credit risk.',true,true,'verified_reference'),
 ('CA-CP-REF','Canadian Commercial Paper — Research Reference','Canadian Commercial Paper Research Reference','COMMERCIAL_PAPER',null,'Money Market','Corporate','Short-term unsecured corporate funding','Canada','CA','CAD','REFERENCE','Educational reference for Canadian commercial paper. It is not a live quoted issue and intentionally does not display an invented current yield.',true,true,'identity_only'),
 ('CA-ABCP-REF','Canadian ABCP — Research Reference','Canadian Asset-Backed Commercial Paper Research Reference','ABCP',null,'Money Market','Asset-Backed','Short-term asset-backed funding','Canada','CA','CAD','REFERENCE','Educational reference for Canadian asset-backed commercial paper. It illustrates structure and liquidity/credit considerations without pretending to be a live issue.',true,true,'identity_only')
on conflict (symbol,exchange) do update set
 name=excluded.name,legal_name=excluded.legal_name,asset_type=excluded.asset_type,issuer_id=excluded.issuer_id,category=excluded.category,subcategory=excluded.subcategory,strategy=excluded.strategy,region=excluded.region,country_code=excluded.country_code,currency=excluded.currency,description=excluded.description,is_active=true,is_featured=excluded.is_featured,data_status=excluded.data_status,updated_at=now();

insert into public.investment_structure_profiles(investment_id,model_version,capital_protection,liquidity_level,price_volatility,income_predictability,growth_participation,interest_rate_sensitivity,credit_exposure,diversification_level,complexity_level,time_structure,principal_protection_basis,source_basis,as_of_date)
select i.id,'structure-v1',x.capital_protection,x.liquidity_level,x.price_volatility,x.income_predictability,x.growth_participation,x.interest_rate_sensitivity,x.credit_exposure,x.diversification_level,x.complexity_level,x.time_structure,x.principal_protection_basis,x.source_basis::jsonb,x.as_of_date
from (values
 ('RBC-GIC-1Y-NR','insured_deposit','locked','none','very_high','none','low','Royal Bank of Canada deposit','single_issuer','low','locked_term','Principal is repayable at maturity; eligible deposits at CDIC member institutions may be protected within applicable CDIC category limits','{"product_source":"RBC","insurance_source":"CDIC"}','2026-09-11'::date),
 ('RBC-GIC-5Y-NR','insured_deposit','locked','none','very_high','none','low','Royal Bank of Canada deposit','single_issuer','low','locked_term','Principal is repayable at maturity; eligible deposits at CDIC member institutions may be protected within applicable CDIC category limits','{"product_source":"RBC","insurance_source":"CDIC"}','2026-09-11'::date),
 ('RBC-GIC-1Y-CASH','insured_deposit','medium','none','high','none','low','Royal Bank of Canada deposit','single_issuer','low','locked_term','Principal is contractual; early access is subject to cashable-product rules and eligible deposits may be protected within applicable CDIC category limits','{"product_source":"RBC","insurance_source":"CDIC"}','2026-09-11'::date),
 ('RBC-GIC-3Y-RED','insured_deposit','medium','none','high','none','low','Royal Bank of Canada deposit','single_issuer','low','locked_term','Principal is contractual; redemption before maturity can reduce the rate received and eligible deposits may be protected within applicable CDIC category limits','{"product_source":"RBC","insurance_source":"CDIC"}','2026-09-11'::date),
 ('GOC-TBILL-3M','contractual','high','very_low','high','none','low','Government of Canada','single_issuer','low','short_term','Government of Canada obligation; market value can vary before maturity','{"source":"Bank of Canada"}','2026-09-14'::date),
 ('GOC-TBILL-6M','contractual','high','very_low','high','none','low','Government of Canada','single_issuer','low','short_term','Government of Canada obligation; market value can vary before maturity','{"source":"Bank of Canada"}','2026-09-14'::date),
 ('GOC-TBILL-1Y','contractual','high','very_low','high','none','low','Government of Canada','single_issuer','low','short_term','Government of Canada obligation; market value can vary before maturity','{"source":"Bank of Canada"}','2026-09-14'::date),
 ('GOC-BOND-2Y','contractual','high','low','high','none','low','Government of Canada','single_issuer','low','fixed_maturity','Government of Canada obligation; price can move before maturity','{"source":"Bank of Canada"}','2026-09-14'::date),
 ('GOC-BOND-5Y','contractual','high','medium','high','none','medium','Government of Canada','single_issuer','low','fixed_maturity','Government of Canada obligation; price can move before maturity','{"source":"Bank of Canada"}','2026-09-14'::date),
 ('GOC-BOND-10Y','contractual','high','medium','high','none','high','Government of Canada','single_issuer','low','fixed_maturity','Government of Canada obligation; longer duration can create larger price changes before maturity','{"source":"Bank of Canada"}','2026-09-14'::date),
 ('GOC-BOND-LONG','contractual','high','high','high','none','high','Government of Canada','single_issuer','low','fixed_maturity','Government of Canada obligation; long duration can create substantial price sensitivity before maturity','{"source":"Bank of Canada"}','2026-09-14'::date),
 ('ON-BOND-2031','conditional','medium','medium','high','none','medium','Province of Ontario','single_issuer','low','fixed_maturity','Repayment depends on the provincial issuer meeting its obligations; secondary-market value can vary','{"source":"Ontario Financing Authority"}','2026-09-15'::date),
 ('BELL-M69-2036','conditional','medium','medium','high','none','high','Bell Canada / BCE corporate credit','single_issuer','medium','fixed_maturity','Repayment depends on the corporate issuer/guarantor meeting its obligations; secondary-market value can vary','{"source":"Bell Canada"}','2026-09-15'::date),
 ('CA-CP-REF','conditional','medium','very_low','high','none','low','Short-term corporate issuer credit','single_issuer','medium','short_term','No deposit insurance; repayment depends on the issuing company and specific paper','{"source":"Bank of Canada educational reference"}','2026-09-15'::date),
 ('CA-ABCP-REF','conditional','medium','low','high','none','low','Asset pool plus program liquidity/credit support','limited','high','short_term','No deposit insurance; repayment depends on the securitized asset/program structure and support arrangements','{"source":"Canadian Fixed-Income Forum / Bank of Canada educational reference"}','2026-09-15'::date)
) as x(symbol,capital_protection,liquidity_level,price_volatility,income_predictability,growth_participation,interest_rate_sensitivity,credit_exposure,diversification_level,complexity_level,time_structure,principal_protection_basis,source_basis,as_of_date)
join public.investments i on i.symbol=x.symbol
on conflict (investment_id,model_version) do update set
 capital_protection=excluded.capital_protection,liquidity_level=excluded.liquidity_level,price_volatility=excluded.price_volatility,income_predictability=excluded.income_predictability,growth_participation=excluded.growth_participation,interest_rate_sensitivity=excluded.interest_rate_sensitivity,credit_exposure=excluded.credit_exposure,diversification_level=excluded.diversification_level,complexity_level=excluded.complexity_level,time_structure=excluded.time_structure,principal_protection_basis=excluded.principal_protection_basis,source_basis=excluded.source_basis,as_of_date=excluded.as_of_date,updated_at=now();

insert into public.investment_deposit_terms(investment_id,annual_rate_pct,term_months,redeemability,minimum_deposit,interest_payment_frequency,registered_account_eligibility,deposit_insurance_scheme,deposit_insurance_eligible,lockup_note,source_name,source_url,as_of_date)
select i.id,x.annual_rate_pct,x.term_months,x.redeemability,null,x.payment_frequency,'{}'::text[],'CDIC',true,x.lockup_note,'RBC Royal Bank','https://www.rbcroyalbank.com/services/gic-rates/special/index-1.html','2026-09-11'::date
from (values
 ('RBC-GIC-1Y-NR',2.45::numeric,12,'non_redeemable','At maturity or according to the selected interest-payment option.','Not redeemable before maturity under the standard non-redeemable terms.'),
 ('RBC-GIC-5Y-NR',2.75::numeric,60,'non_redeemable','Annually, semi-annually or at maturity depending on the selected option.','Not redeemable before maturity under the standard non-redeemable terms.'),
 ('RBC-GIC-1Y-CASH',1.95::numeric,12,'redeemable','Semi-annually or at maturity.','Cashable subject to product rules; early redemption rates can differ from the headline rate.'),
 ('RBC-GIC-3Y-RED',2.45::numeric,36,'redeemable','Annually, semi-annually or at maturity depending on the selected option.','Redeemable, but prior-redemption rates are lower than the full-term posted rate.')
) as x(symbol,annual_rate_pct,term_months,redeemability,payment_frequency,lockup_note)
join public.investments i on i.symbol=x.symbol
on conflict (investment_id,term_months,redeemability,as_of_date) do update set annual_rate_pct=excluded.annual_rate_pct,interest_payment_frequency=excluded.interest_payment_frequency,deposit_insurance_scheme=excluded.deposit_insurance_scheme,deposit_insurance_eligible=excluded.deposit_insurance_eligible,lockup_note=excluded.lockup_note,source_name=excluded.source_name,source_url=excluded.source_url;

insert into public.investment_fixed_income_terms(investment_id,instrument_subtype,coupon_pct,yield_to_maturity_pct,issue_date,maturity_date,remaining_term_months,duration_years,face_value,credit_rating,credit_rating_agency,discount_instrument,market_access_note,source_name,source_url,as_of_date)
select i.id,x.instrument_subtype,x.coupon_pct,x.ytm,x.issue_date,x.maturity_date,x.term_months,null,x.face_value,x.credit_rating,x.rating_agency,x.discount_instrument,x.market_access_note,x.source_name,x.source_url,x.as_of_date
from (values
 ('GOC-TBILL-3M','Government of Canada 3-month Treasury Bill',null::numeric,2.34::numeric,null::date,null::date,3,1000::numeric,null::text,null::text,true,'Reference yield from the Bank of Canada secondary-market series; individual bill prices and maturities vary.','Bank of Canada','https://www.bankofcanada.ca/rates/interest-rates/money-market-yields/','2026-09-14'::date),
 ('GOC-TBILL-6M','Government of Canada 6-month Treasury Bill',null::numeric,2.62::numeric,null::date,null::date,6,1000::numeric,null::text,null::text,true,'Reference yield from the Bank of Canada secondary-market series; individual bill prices and maturities vary.','Bank of Canada','https://www.bankofcanada.ca/rates/interest-rates/money-market-yields/','2026-09-14'::date),
 ('GOC-TBILL-1Y','Government of Canada 1-year Treasury Bill',null::numeric,3.05::numeric,null::date,null::date,12,1000::numeric,null::text,null::text,true,'Reference yield from the Bank of Canada secondary-market series; individual bill prices and maturities vary.','Bank of Canada','https://www.bankofcanada.ca/rates/interest-rates/money-market-yields/','2026-09-14'::date),
 ('GOC-BOND-2Y','Government of Canada benchmark nominal bond',2.75::numeric,3.37::numeric,null::date,'2028-08-01'::date,null::int,1000::numeric,null::text,null::text,false,'Selected benchmark yield based on mid-market closing yields; the benchmark issue can change over time.','Bank of Canada','https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/','2026-09-14'::date),
 ('GOC-BOND-5Y','Government of Canada benchmark nominal bond',3.00::numeric,3.65::numeric,null::date,'2031-09-01'::date,null::int,1000::numeric,null::text,null::text,false,'Selected benchmark yield based on mid-market closing yields; current benchmark effective September 10, 2026.','Bank of Canada','https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/','2026-09-14'::date),
 ('GOC-BOND-10Y','Government of Canada benchmark nominal bond',3.25::numeric,3.94::numeric,null::date,'2036-06-01'::date,null::int,1000::numeric,null::text,null::text,false,'Selected benchmark yield based on mid-market closing yields; the benchmark issue can change over time.','Bank of Canada','https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/','2026-09-14'::date),
 ('GOC-BOND-LONG','Government of Canada long benchmark nominal bond',3.50::numeric,4.27::numeric,null::date,'2057-12-01'::date,null::int,1000::numeric,null::text,null::text,false,'Selected long-term benchmark yield based on mid-market closing yields.','Bank of Canada','https://www.bankofcanada.ca/rates/interest-rates/canadian-bonds/','2026-09-14'::date),
 ('ON-BOND-2031','Province of Ontario DMTN253',2.25::numeric,null::numeric,'2021-10-14'::date,'2031-12-02'::date,null::int,1000::numeric,null::text,null::text,false,'Official issue terms shown for research. A current secondary-market yield is intentionally not synthesized.','Ontario Financing Authority','https://www.ofina.on.ca/pdf/bond_issue_details_DMTN253_to_R7.pdf','2026-09-15'::date),
 ('BELL-M69-2036','Bell Canada MTN Debenture Series M-69',4.70::numeric,null::numeric,'2026-06-03'::date,'2036-11-15'::date,null::int,100::numeric,null::text,null::text,false,'Public Canadian corporate debenture. The offering yield was 4.723% at issue; no current secondary-market yield is displayed here.','Bell Canada','https://www.bce.ca/news-and-media/newsroom?article=bell-announces-offerings-of-canadian-mtn-debentures-and-us-notes','2026-09-15'::date),
 ('CA-CP-REF','Canadian investment-grade commercial paper reference',null::numeric,null::numeric,null::date,null::date,null::int,null::numeric,null::text,null::text,true,'Educational structure only. Commercial paper is short-term dealer-market corporate funding and issue-level terms change rapidly.','Bank of Canada','https://www.bankofcanada.ca/markets/market-operations-liquidity-provision/market-operations-programs-and-facilities/commercial-paper-purchase-program/','2026-09-15'::date),
 ('CA-ABCP-REF','Canadian asset-backed commercial paper reference',null::numeric,null::numeric,null::date,null::date,null::int,null::numeric,null::text,null::text,true,'Educational structure only. ABCP exposure depends on the underlying asset pool, conduit and liquidity/credit support.','Bank of Canada / Canadian Fixed-Income Forum','https://www.bankofcanada.ca/2024/06/cfif-batvn-publishes-educational-primer-canadian-asset-backed-commercial-paper/','2026-09-15'::date)
) as x(symbol,instrument_subtype,coupon_pct,ytm,issue_date,maturity_date,term_months,face_value,credit_rating,rating_agency,discount_instrument,market_access_note,source_name,source_url,as_of_date)
join public.investments i on i.symbol=x.symbol
on conflict (investment_id,instrument_subtype,as_of_date) do update set coupon_pct=excluded.coupon_pct,yield_to_maturity_pct=excluded.yield_to_maturity_pct,issue_date=excluded.issue_date,maturity_date=excluded.maturity_date,remaining_term_months=excluded.remaining_term_months,face_value=excluded.face_value,discount_instrument=excluded.discount_instrument,market_access_note=excluded.market_access_note,source_name=excluded.source_name,source_url=excluded.source_url;

insert into public.investment_structure_profiles(investment_id,model_version,capital_protection,liquidity_level,price_volatility,income_predictability,growth_participation,interest_rate_sensitivity,credit_exposure,diversification_level,complexity_level,time_structure,principal_protection_basis,source_basis,as_of_date)
select d.investment_id,'structure-v1','none','high',
 case coalesce(d.official_risk_rating,d.risk_band)
  when 'Low' then 'low' when 'Low to Medium' then 'low' when 'Medium' then 'medium' when 'Medium to High' then 'high' when 'High' then 'very_high' else null end,
 case when d.income_score is null then null when d.income_score<20 then 'low' when d.income_score<60 then 'medium' else 'high' end,
 case when d.growth_score is null then null when d.growth_score<40 then 'low' when d.growth_score<75 then 'medium' else 'high' end,
 case when coalesce(d.fixed_income_pct,0)>=50 then 'medium' else 'not_applicable' end,
 'Diversified fund holdings','diversified','medium','open_ended','No contractual principal protection; market value fluctuates',jsonb_build_object('derived_from','v_investment_dna_v2','model',d.intelligence_model_version),greatest(d.as_of_date,current_date-1)
from public.v_investment_dna_v2 d
where d.asset_type='ETF'
on conflict (investment_id,model_version) do update set capital_protection=excluded.capital_protection,liquidity_level=excluded.liquidity_level,price_volatility=excluded.price_volatility,income_predictability=excluded.income_predictability,growth_participation=excluded.growth_participation,interest_rate_sensitivity=excluded.interest_rate_sensitivity,credit_exposure=excluded.credit_exposure,diversification_level=excluded.diversification_level,complexity_level=excluded.complexity_level,time_structure=excluded.time_structure,principal_protection_basis=excluded.principal_protection_basis,source_basis=excluded.source_basis,as_of_date=excluded.as_of_date,updated_at=now();
